package com.ftk.tpip.adapters.persistence.jdbc.integration;

import com.ftk.tpip.integration.domain.exception.*;import com.ftk.tpip.integration.domain.model.*;import com.ftk.tpip.integration.domain.repository.IntegrationPolicyRepository;import com.ftk.tpip.shared.AssetCode;import java.sql.*;import java.util.*;import org.springframework.dao.DuplicateKeyException;import org.springframework.jdbc.core.*;import org.springframework.jdbc.core.namedparam.*;import org.springframework.jdbc.support.GeneratedKeyHolder;

public class JdbcIntegrationPolicyRepository implements IntegrationPolicyRepository{
private static final String P="id,binding_id,policy_code,policy_name,status,row_version,created_at,updated_at";private static final String V="id,policy_id,version_no,dsl_api_version,normalized_document,compiler_version,compile_status,compile_diagnostics,content_checksum,lifecycle_status,published_at,created_at";private static final RowMapper<IntegrationPolicy> PM=(r,n)->new IntegrationPolicy(r.getLong("id"),r.getLong("binding_id"),AssetCode.of(r.getString("policy_code")),r.getString("policy_name"),PolicyStatus.valueOf(r.getString("status")),r.getLong("row_version"),r.getTimestamp("created_at").toInstant(),r.getTimestamp("updated_at").toInstant());private static final RowMapper<IntegrationPolicyVersion> VM=(r,n)->{var p=r.getTimestamp("published_at");return new IntegrationPolicyVersion(r.getLong("id"),r.getLong("policy_id"),r.getInt("version_no"),r.getString("dsl_api_version"),r.getString("normalized_document"),r.getString("compiler_version"),PolicyCompileStatus.valueOf(r.getString("compile_status")),r.getString("compile_diagnostics"),r.getString("content_checksum"),PolicyLifecycleStatus.valueOf(r.getString("lifecycle_status")),p==null?null:p.toInstant(),r.getTimestamp("created_at").toInstant());};private final JdbcTemplate j;private final NamedParameterJdbcTemplate n;public JdbcIntegrationPolicyRepository(JdbcTemplate j){this.j=j;this.n=new NamedParameterJdbcTemplate(j);}
public Optional<IntegrationPolicy> findById(long id){return j.query("SELECT "+P+" FROM tpip_policy WHERE id=?",PM,id).stream().findFirst();}public Optional<IntegrationPolicy> findByCode(AssetCode code){return j.query("SELECT "+P+" FROM tpip_policy WHERE policy_code=?",PM,code.value()).stream().findFirst();}public List<IntegrationPolicy> findAll(IntegrationPolicyQuery q){var x=parts(q);return n.query("SELECT "+P+" FROM tpip_policy"+x.w+" ORDER BY id DESC LIMIT :l OFFSET :o",x.p.addValue("l",q.limit()).addValue("o",q.offset()),PM);}public long count(IntegrationPolicyQuery q){var x=parts(q);Long v=n.queryForObject("SELECT COUNT(*) FROM tpip_policy"+x.w,x.p,Long.class);return v==null?0:v;}
public IntegrationPolicy create(IntegrationPolicy p,String a){var k=new GeneratedKeyHolder();try{j.update(c->{var s=c.prepareStatement("INSERT INTO tpip_policy(binding_id,policy_code,policy_name,status,row_version,created_by,updated_by) VALUES(?,?,?,?,0,?,?)",Statement.RETURN_GENERATED_KEYS);s.setLong(1,p.bindingId());s.setString(2,p.policyCode().value());s.setString(3,p.policyName());s.setString(4,p.status().name());s.setString(5,a);s.setString(6,a);return s;},k);}catch(DuplicateKeyException e){throw new PolicyCodeAlreadyExistsException(p.policyCode().value());}if(k.getKey()==null)throw new IllegalStateException("MySQL did not return policy id");var x=findById(k.getKey().longValue()).orElseThrow();audit("POLICY_CREATED",x.policyCode().value(),null,a,"Created policy");return x;}
public IntegrationPolicy update(IntegrationPolicy p,String a){int x=j.update("UPDATE tpip_policy SET policy_name=?,status=?,row_version=row_version+1,updated_by=? WHERE id=? AND row_version=?",p.policyName(),p.status().name(),a,p.id(),p.rowVersion());if(x==0)throw new PolicyConcurrentModificationException(p.id(),p.rowVersion());var r=findById(p.id()).orElseThrow();audit("POLICY_UPDATED",r.policyCode().value(),null,a,"Updated policy metadata");return r;}
public Optional<IntegrationPolicyVersion> findVersion(long p,long v){return j.query("SELECT "+V+" FROM tpip_policy_version WHERE policy_id=? AND id=?",VM,p,v).stream().findFirst();}public Optional<IntegrationPolicyVersion> findVersionById(long v){return j.query("SELECT "+V+" FROM tpip_policy_version WHERE id=?",VM,v).stream().findFirst();}public List<IntegrationPolicyVersion> findVersions(long p){return j.query("SELECT "+V+" FROM tpip_policy_version WHERE policy_id=? ORDER BY version_no DESC",VM,p);}
public IntegrationPolicyVersion createVersion(IntegrationPolicyVersion v,String a){j.queryForObject("SELECT id FROM tpip_policy WHERE id=? FOR UPDATE",Long.class,v.policyId());Integer no=j.queryForObject("SELECT COALESCE(MAX(version_no),0)+1 FROM tpip_policy_version WHERE policy_id=?",Integer.class,v.policyId());var k=new GeneratedKeyHolder();j.update(c->{var s=c.prepareStatement("INSERT INTO tpip_policy_version(policy_id,version_no,dsl_api_version,normalized_document,compiler_version,compile_status,compile_diagnostics,content_checksum,lifecycle_status,created_by) VALUES(?,?,?,?,?,?,?,?, 'DRAFT',?)",Statement.RETURN_GENERATED_KEYS);s.setLong(1,v.policyId());s.setInt(2,no==null?1:no);s.setString(3,v.dslApiVersion());s.setString(4,v.normalizedDocument());s.setString(5,v.compilerVersion());s.setString(6,v.compileStatus().name());s.setString(7,v.compileDiagnostics());s.setString(8,v.contentChecksum());s.setString(9,a);return s;},k);if(k.getKey()==null)throw new IllegalStateException("MySQL did not return policy version id");var r=findVersion(v.policyId(),k.getKey().longValue()).orElseThrow();var p=findById(v.policyId()).orElseThrow();audit("POLICY_VERSION_CREATED",p.policyCode().value(),Integer.toString(r.versionNo()),a,"Created compiled policy version");return r;}
public IntegrationPolicyVersion publishVersion(long p,long v,String a){int x=j.update("UPDATE tpip_policy_version SET lifecycle_status='PUBLISHED',published_at=CURRENT_TIMESTAMP(3) WHERE policy_id=? AND id=? AND lifecycle_status='DRAFT' AND compile_status='COMPILED'",p,v);if(x==0)throw new PolicyVersionLifecycleException(v,"only a compiled DRAFT version can be published");var r=findVersion(p,v).orElseThrow();var d=findById(p).orElseThrow();audit("POLICY_VERSION_PUBLISHED",d.policyCode().value(),Integer.toString(r.versionNo()),a,"Published policy version");return r;}
private void audit(String t,String c,String v,String a,String s){j.update("INSERT INTO tpip_audit_event(event_id,event_type,actor_type,actor_code,asset_type,asset_code,asset_version,event_summary) VALUES(UUID(),?,'USER',?,'POLICY',?,?,?)",t,a,c,v,s);}private static Q parts(IntegrationPolicyQuery q){List<String>x=new ArrayList<>();var p=new MapSqlParameterSource();if(q.bindingId()!=null){x.add("binding_id=:b");p.addValue("b",q.bindingId());}if(q.keyword()!=null){x.add("(policy_code LIKE :k OR policy_name LIKE :k)");p.addValue("k","%"+q.keyword()+"%");}if(q.status()!=null){x.add("status=:s");p.addValue("s",q.status().name());}return new Q(x.isEmpty()?"":" WHERE "+String.join(" AND ",x),p);}private record Q(String w,MapSqlParameterSource p){}
}
