package com.ftk.tpip.adapters.persistence.jdbc.integration;

import com.fasterxml.jackson.core.JsonProcessingException;import com.fasterxml.jackson.databind.ObjectMapper;
import com.ftk.tpip.integration.domain.exception.PolicyTypeAlreadyExistsException;import com.ftk.tpip.integration.domain.model.*;import com.ftk.tpip.integration.domain.repository.PolicyTypeRepository;import com.ftk.tpip.shared.*;
import java.sql.*;import java.util.*;import org.springframework.dao.DuplicateKeyException;import org.springframework.jdbc.core.*;import org.springframework.jdbc.support.GeneratedKeyHolder;

public class JdbcPolicyTypeRepository implements PolicyTypeRepository{
private static final String C="id,policy_type_code,semantic_version,implementation_kind,allowed_stages,configuration_schema,runtime_compatibility,security_classification,deterministic_flag,side_effect_flag,idempotency_requirement,implementation_ref,artifact_checksum,status,created_at";private final JdbcTemplate j;private final ObjectMapper json;public JdbcPolicyTypeRepository(JdbcTemplate j,ObjectMapper json){this.j=j;this.json=json;}
private PolicyTypeDefinition map(ResultSet r,int n)throws SQLException{String idem=r.getString("idempotency_requirement");return new PolicyTypeDefinition(r.getLong("id"),AssetCode.of(r.getString("policy_type_code")),SemanticVersion.parse(r.getString("semantic_version")),PolicyImplementationKind.valueOf(r.getString("implementation_kind")),stages(r.getString("allowed_stages")),r.getString("configuration_schema"),r.getString("runtime_compatibility"),PolicySecurityClassification.valueOf(r.getString("security_classification")),r.getBoolean("deterministic_flag"),r.getBoolean("side_effect_flag"),idem==null?null:PolicyIdempotencyRequirement.valueOf(idem),r.getString("implementation_ref"),r.getString("artifact_checksum"),PolicyTypeStatus.valueOf(r.getString("status")),r.getTimestamp("created_at").toInstant());}
public Optional<PolicyTypeDefinition> findById(long id){return j.query("SELECT "+C+" FROM tpip_policy_type WHERE id=?",this::map,id).stream().findFirst();}public Optional<PolicyTypeDefinition> findByReference(String code,String version){return j.query("SELECT "+C+" FROM tpip_policy_type WHERE policy_type_code=? AND semantic_version=?",this::map,code,version).stream().findFirst();}public List<PolicyTypeDefinition> findAll(Boolean activeOnly){return activeOnly!=null&&activeOnly?j.query("SELECT "+C+" FROM tpip_policy_type WHERE status='ACTIVE' ORDER BY policy_type_code,semantic_version",this::map):j.query("SELECT "+C+" FROM tpip_policy_type ORDER BY policy_type_code,semantic_version",this::map);}
public PolicyTypeDefinition create(PolicyTypeDefinition d,String actor){var k=new GeneratedKeyHolder();try{j.update(c->{var s=c.prepareStatement("INSERT INTO tpip_policy_type(policy_type_code,semantic_version,implementation_kind,allowed_stages,configuration_schema,runtime_compatibility,security_classification,deterministic_flag,side_effect_flag,idempotency_requirement,implementation_ref,artifact_checksum,status,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)",Statement.RETURN_GENERATED_KEYS);s.setString(1,d.policyTypeCode().value());s.setString(2,d.semanticVersion().toString());s.setString(3,d.implementationKind().name());s.setString(4,write(d.allowedStages().stream().map(Enum::name).sorted().toList()));s.setString(5,d.configurationSchema());s.setString(6,d.runtimeCompatibility());s.setString(7,d.securityClassification().name());s.setBoolean(8,d.deterministic());s.setBoolean(9,d.sideEffect());s.setString(10,d.idempotencyRequirement()==null?null:d.idempotencyRequirement().name());s.setString(11,d.implementationRef());s.setString(12,d.artifactChecksum());s.setString(13,d.status().name());s.setString(14,actor);return s;},k);}catch(DuplicateKeyException e){throw new PolicyTypeAlreadyExistsException(d.policyTypeCode()+"@"+d.semanticVersion());}if(k.getKey()==null)throw new IllegalStateException("MySQL did not return policy type id");var x=findById(k.getKey().longValue()).orElseThrow();audit("POLICY_TYPE_REGISTERED",x.policyTypeCode().value(),x.semanticVersion().toString(),actor,"Registered policy type");return x;}
public PolicyTypeDefinition setStatus(long id,PolicyTypeStatus status,String actor){int n=j.update("UPDATE tpip_policy_type SET status=? WHERE id=?",status.name(),id);if(n==0)throw new IllegalArgumentException("Policy type does not exist: "+id);var x=findById(id).orElseThrow();audit("POLICY_TYPE_STATUS_CHANGED",x.policyTypeCode().value(),x.semanticVersion().toString(),actor,"Changed policy type status to "+status);return x;}
private Set<PolicyMountStage> stages(String value){try{Set<PolicyMountStage>x=EnumSet.noneOf(PolicyMountStage.class);for(String s:json.readValue(value,String[].class))x.add(PolicyMountStage.valueOf(s));return x;}catch(Exception e){throw new IllegalStateException("Stored allowed_stages is invalid",e);}}private String write(Object value){try{return json.writeValueAsString(value);}catch(JsonProcessingException e){throw new IllegalArgumentException("Cannot serialize policy type",e);}}private void audit(String t,String c,String v,String a,String s){j.update("INSERT INTO tpip_audit_event(event_id,event_type,actor_type,actor_code,asset_type,asset_code,asset_version,event_summary) VALUES(UUID(),?,'USER',?,'POLICY_TYPE',?,?,?)",t,a,c,v,s);}}
