package com.ftk.tpip.policy.compiler;

import static org.junit.jupiter.api.Assertions.*;import com.fasterxml.jackson.databind.*;import com.ftk.tpip.policy.api.*;import com.ftk.tpip.shared.*;import java.util.*;import org.junit.jupiter.api.Test;
class DefaultPolicyCompilerTest{private final ObjectMapper json=new ObjectMapper();private final DefaultPolicyCompiler compiler=new DefaultPolicyCompiler(json);
@Test void compilesRegisteredPolicyIntoFixedStages()throws Exception{var plan=compiler.compile(document("{\"apiVersion\":\"tpip.policy/v1alpha1\",\"kind\":\"PolicyChain\",\"stages\":{\"AFTER_REQUEST_MAPPING\":[{\"id\":\"inject-request-id\",\"use\":\"builtin.transport.inject@1.0.0\",\"with\":{\"headers\":{\"X-Request-Id\":\"${context.requestId}\"}}}]}}"),registry(inject()));assertEquals(1,plan.stages().get(PolicyStage.AFTER_REQUEST_MAPPING).size());assertEquals(64,plan.checksum().length());}
@Test void rejectsUnregisteredType()throws Exception{var ex=assertThrows(PolicyCompilationException.class,()->compiler.compile(document("{\"apiVersion\":\"tpip.policy/v1alpha1\",\"kind\":\"PolicyChain\",\"stages\":{\"BEFORE_TRANSPORT\":[{\"id\":\"unknown\",\"use\":\"builtin.unknown@1.0.0\"}]}}"),registry(inject())));assertTrue(ex.diagnostics().stream().anyMatch(d->d.code().equals("POLICY_TYPE_NOT_REGISTERED")));}
@Test void rejectsIllegalStageAndSensitiveContinue()throws Exception{var apiKey=descriptor("builtin.auth.api-key",Set.of(PolicyStage.BEFORE_TRANSPORT),"CRITICAL","{\"type\":\"object\",\"properties\":{\"secretRef\":{\"type\":\"string\",\"format\":\"secret-ref\"}},\"required\":[\"secretRef\"],\"additionalProperties\":false}");var ex=assertThrows(PolicyCompilationException.class,()->compiler.compile(document("{\"apiVersion\":\"tpip.policy/v1alpha1\",\"kind\":\"PolicyChain\",\"stages\":{\"AFTER_REQUEST_MAPPING\":[{\"id\":\"api-key\",\"use\":\"builtin.auth.api-key@1.0.0\",\"with\":{\"secretRef\":\"secret://provider/prod/key\"},\"onFailure\":\"CONTINUE\"}]}}"),registry(apiKey)));assertTrue(ex.diagnostics().stream().anyMatch(d->d.code().equals("POLICY_STAGE_NOT_ALLOWED")));assertTrue(ex.diagnostics().stream().anyMatch(d->d.code().equals("POLICY_SECURITY_FAILURE_CANNOT_CONTINUE")));}
@Test void rejectsUnsafeCondition()throws Exception{var ex=assertThrows(PolicyCompilationException.class,()->compiler.compile(document("{\"apiVersion\":\"tpip.policy/v1alpha1\",\"kind\":\"PolicyChain\",\"stages\":{\"AFTER_REQUEST_MAPPING\":[{\"id\":\"inject\",\"use\":\"builtin.transport.inject@1.0.0\",\"when\":\"System.exit(0)\",\"with\":{\"headers\":{}}}]}}"),registry(inject())));assertTrue(ex.diagnostics().stream().anyMatch(d->d.code().equals("POLICY_CONDITION_INVALID")));}
@Test void rejectsSecretValueInsteadOfReference()throws Exception{var apiKey=descriptor("builtin.auth.api-key",Set.of(PolicyStage.BEFORE_TRANSPORT),"CRITICAL","{\"type\":\"object\",\"properties\":{\"secretRef\":{\"type\":\"string\",\"format\":\"secret-ref\"}},\"required\":[\"secretRef\"],\"additionalProperties\":false}");var ex=assertThrows(PolicyCompilationException.class,()->compiler.compile(document("{\"apiVersion\":\"tpip.policy/v1alpha1\",\"kind\":\"PolicyChain\",\"stages\":{\"BEFORE_TRANSPORT\":[{\"id\":\"api-key\",\"use\":\"builtin.auth.api-key@1.0.0\",\"with\":{\"secretRef\":\"plaintext-key\"}}]}}"),registry(apiKey)));assertTrue(ex.diagnostics().stream().anyMatch(d->d.code().equals("POLICY_CONFIGURATION_INVALID")));}
@Test void acceptsEnvironmentSecretReference()throws Exception{var apiKey=descriptor("builtin.auth.api-key",Set.of(PolicyStage.BEFORE_TRANSPORT),"CRITICAL","{\"type\":\"object\",\"properties\":{\"secretRef\":{\"type\":\"string\",\"format\":\"secret-ref\"}},\"required\":[\"secretRef\"],\"additionalProperties\":false}");var plan=compiler.compile(document("{\"apiVersion\":\"tpip.policy/v1alpha1\",\"kind\":\"PolicyChain\",\"stages\":{\"BEFORE_TRANSPORT\":[{\"id\":\"api-key\",\"use\":\"builtin.auth.api-key@1.0.0\",\"with\":{\"secretRef\":\"env://TPIP_SECRET_PROVIDER_KEY\"}}]}}"),registry(apiKey));assertEquals("env://TPIP_SECRET_PROVIDER_KEY",plan.stages().get(PolicyStage.BEFORE_TRANSPORT).getFirst().parameters().get("secretRef"));}
@Test void acceptsBooleanLiteralInSafeCondition()throws Exception{var plan=compiler.compile(document("{\"apiVersion\":\"tpip.policy/v1alpha1\",\"kind\":\"PolicyChain\",\"stages\":{\"AFTER_REQUEST_MAPPING\":[{\"id\":\"inject\",\"use\":\"builtin.transport.inject@1.0.0\",\"when\":\"context.enabled == true\",\"with\":{\"headers\":{}}}]}}"),registry(inject()));assertEquals("context.enabled == true",plan.stages().get(PolicyStage.AFTER_REQUEST_MAPPING).getFirst().conditionExpression());}
@Test void rejectsMalformedInterpolationAfterAValidOne()throws Exception{var ex=assertThrows(PolicyCompilationException.class,()->compiler.compile(document("{\"apiVersion\":\"tpip.policy/v1alpha1\",\"kind\":\"PolicyChain\",\"stages\":{\"AFTER_REQUEST_MAPPING\":[{\"id\":\"inject\",\"use\":\"builtin.transport.inject@1.0.0\",\"with\":{\"headers\":{\"X-Test\":\"${context.requestId}-${broken\"}}}]}}"),registry(inject())));assertTrue(ex.diagnostics().stream().anyMatch(d->d.code().equals("POLICY_INTERPOLATION_INVALID")));}
@Test void producesStableChecksumForDifferentConfigurationKeyOrder()throws Exception{var first=compiler.compile(document("{\"apiVersion\":\"tpip.policy/v1alpha1\",\"kind\":\"PolicyChain\",\"stages\":{\"AFTER_REQUEST_MAPPING\":[{\"id\":\"inject\",\"use\":\"builtin.transport.inject@1.0.0\",\"with\":{\"headers\":{\"X-B\":\"b\",\"X-A\":\"a\"}}}]}}"),registry(inject()));var second=compiler.compile(document("{\"kind\":\"PolicyChain\",\"stages\":{\"AFTER_REQUEST_MAPPING\":[{\"use\":\"builtin.transport.inject@1.0.0\",\"id\":\"inject\",\"with\":{\"headers\":{\"X-A\":\"a\",\"X-B\":\"b\"}}}]},\"apiVersion\":\"tpip.policy/v1alpha1\"}"),registry(inject()));assertEquals(first.checksum(),second.checksum());}
private PolicyDocument document(String value)throws Exception{return new PolicyDocument(AssetCode.of("provider.refund.policy"),1,DefaultPolicyCompiler.DSL_API_VERSION,json.readTree(value));}private PolicyTypeRegistrySnapshot registry(PolicyTypeDescriptor...values){return new PolicyTypeRegistrySnapshot(List.of(values));}private PolicyTypeDescriptor inject()throws Exception{return descriptor("builtin.transport.inject",Set.of(PolicyStage.AFTER_REQUEST_MAPPING),"NORMAL","{\"type\":\"object\",\"properties\":{\"headers\":{\"type\":\"object\",\"additionalProperties\":{\"type\":\"string\"}}},\"required\":[\"headers\"],\"additionalProperties\":false}");}private PolicyTypeDescriptor descriptor(String code,Set<PolicyStage>stages,String security,String schema)throws Exception{return new PolicyTypeDescriptor(AssetCode.of(code),SemanticVersion.parse("1.0.0"),stages,json.readTree(schema),">=0.1 <1.0",true,false,security,"ANY",true);}}
