package com.ftk.tpip.control.application.release;

import com.fasterxml.jackson.databind.*;
import com.ftk.tpip.bundle.*;
import com.ftk.tpip.control.application.integration.BindingVersionBundlePreviewApplicationService;
import com.ftk.tpip.control.application.provider.CanonicalJsonService;
import com.ftk.tpip.integration.domain.model.*;
import com.ftk.tpip.integration.domain.repository.*;
import com.ftk.tpip.provider.domain.repository.ProviderEndpointRepository;
import com.ftk.tpip.release.domain.model.*;
import com.ftk.tpip.release.domain.repository.ReleaseRepository;
import com.ftk.tpip.shared.AssetCode;
import java.util.*;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
public class ReleaseApplicationService{
 private static final String RELEASE="RELEASE",SECURITY="SECURITY";
 private final ReleaseRepository releases;private final IntegrationBindingRepository bindings;
 private final IntegrationBindingVersionRepository bindingVersions;private final ProviderEndpointRepository endpoints;
 private final BindingVersionBundlePreviewApplicationService previews;private final CanonicalJsonService canonicalJson;
 private final ObjectMapper json;
 public ReleaseApplicationService(ReleaseRepository releases,IntegrationBindingRepository bindings,
        IntegrationBindingVersionRepository bindingVersions,ProviderEndpointRepository endpoints,
        BindingVersionBundlePreviewApplicationService previews,CanonicalJsonService canonicalJson,ObjectMapper json){
    this.releases=releases;this.bindings=bindings;this.bindingVersions=bindingVersions;this.endpoints=endpoints;
    this.previews=previews;this.canonicalJson=canonicalJson;this.json=json;}

 @Transactional public ConfigurationWorkspace create(String code,String name,Long baseBundleId,String environment,
        WorkspaceRiskLevel risk,String owner,String actor){AssetCode c=AssetCode.of(code);if(releases.findWorkspaceByCode(c).isPresent())throw new IllegalArgumentException("Workspace code already exists: "+c.value());if(baseBundleId!=null){var base=bundle(baseBundleId);if(base.lifecycleStatus()!=BundleLifecycleStatus.PUBLISHED)throw new IllegalArgumentException("baseBundleId must be PUBLISHED");if(!base.environmentCode().equals(environment))throw new IllegalArgumentException("baseBundleId environment does not match workspace");}return releases.createWorkspace(ConfigurationWorkspace.draft(c,name,baseBundleId,environment,risk,owner),actor(actor));}
 @Transactional(readOnly=true)public ConfigurationWorkspace get(long id){return releases.findWorkspace(id).orElseThrow(()->new WorkspaceNotFoundException(id));}
 @Transactional(readOnly=true)public List<ConfigurationWorkspace> list(){return releases.findWorkspaces();}
 @Transactional public WorkspaceAsset addBindingVersion(long workspaceId,long bindingId,long versionId,WorkspaceChangeType change,JsonNode metadata,String actor){ConfigurationWorkspace ws=draft(workspaceId);if(!releases.findAssets(workspaceId).isEmpty())throw new IllegalArgumentException("Workspace v0.1 supports exactly one BindingVersion");IntegrationBinding binding=bindings.findById(bindingId).orElseThrow(()->new IllegalArgumentException("bindingId does not exist"));IntegrationBindingVersion version=bindingVersions.findVersion(bindingId,versionId).orElseThrow(()->new IllegalArgumentException("bindingVersionId does not belong to bindingId"));if(version.lifecycleStatus()!=BindingVersionLifecycleStatus.PUBLISHED)throw new IllegalArgumentException("BindingVersion must be PUBLISHED");var endpoint=endpoints.findById(version.endpointId()).orElseThrow();if(!endpoint.environmentCode().equals(ws.environmentCode()))throw new IllegalArgumentException("BindingVersion endpoint environment does not match workspace");String canonical=object(metadata,"dependencyMetadata");return releases.addAsset(new WorkspaceAsset(null,workspaceId,WorkspaceAssetType.BINDING_VERSION,binding.bindingCode().value(),versionId,change,canonical,null),actor(actor));}
 @Transactional(readOnly=true)public List<WorkspaceAsset> assets(long id){get(id);return releases.findAssets(id);}
 @Transactional(readOnly=true)public List<VerificationRun> verifications(long id){get(id);return releases.findVerifications(id);}
 @Transactional public ConfigurationWorkspace submitReview(long id,long rowVersion,String actor){ConfigurationWorkspace ws=get(id);if(releases.findVerifications(id).stream().noneMatch(v->v.status()==VerificationStatus.PASSED&&!releases.findVerificationChecks(v.id()).isEmpty()))throw new IllegalArgumentException("Workspace requires a server-executed PASSED verification");return releases.transitionWorkspace(id,rowVersion,WorkspaceLifecycleStatus.VERIFIED,WorkspaceLifecycleStatus.IN_REVIEW,actor(actor));}
 @Transactional public WorkspaceApproval decide(long id,String stage,ApprovalDecision decision,String comment,JsonNode evidence,long rowVersion,String approver){ConfigurationWorkspace ws=get(id);if(ws.lifecycleStatus()!=WorkspaceLifecycleStatus.IN_REVIEW)throw new com.ftk.tpip.release.domain.exception.WorkspaceLifecycleException(id,"approval requires IN_REVIEW");if(ws.rowVersion()!=rowVersion)throw new com.ftk.tpip.release.domain.exception.WorkspaceConcurrentModificationException(id,rowVersion);String a=actor(approver);if(a.equals(ws.ownerCode()))throw new IllegalArgumentException("Workspace owner cannot approve the same workspace");String normalizedStage=stage.trim().toUpperCase(Locale.ROOT);if(!Set.of(RELEASE,SECURITY).contains(normalizedStage))throw new IllegalArgumentException("approvalStage must be RELEASE or SECURITY");if(releases.findApprovals(id).stream().anyMatch(x->x.approvalStage().equals(normalizedStage)&&x.decision()==ApprovalDecision.APPROVED))throw new IllegalArgumentException("approvalStage is already approved: "+normalizedStage);WorkspaceApproval record=releases.recordApproval(new WorkspaceApproval(null,id,normalizedStage,a,decision,optional(comment,2000),object(evidence,"evidenceSnapshot"),null));if(decision==ApprovalDecision.REJECTED){releases.transitionWorkspace(id,rowVersion,WorkspaceLifecycleStatus.IN_REVIEW,WorkspaceLifecycleStatus.DRAFT,a);return record;}List<WorkspaceApproval> approvals=releases.findApprovals(id);boolean release=approved(approvals,RELEASE);boolean security=approved(approvals,SECURITY);boolean needsSecurity=ws.riskLevel()==WorkspaceRiskLevel.HIGH||ws.riskLevel()==WorkspaceRiskLevel.CRITICAL;if(release&&(!needsSecurity||security)){if(needsSecurity&&approvals.stream().filter(x->x.decision()==ApprovalDecision.APPROVED).map(WorkspaceApproval::approverCode).distinct().count()<2)throw new IllegalArgumentException("HIGH/CRITICAL workspace requires two distinct approvers");releases.transitionWorkspace(id,rowVersion,WorkspaceLifecycleStatus.IN_REVIEW,WorkspaceLifecycleStatus.APPROVED,a);}return record;}
 @Transactional(readOnly=true)public List<WorkspaceApproval> approvals(long id){get(id);return releases.findApprovals(id);}
 @Transactional public DeploymentBundleAsset compile(long workspaceId,String bundleCode,String bundleVersion,long rowVersion,String actor){ConfigurationWorkspace ws=get(workspaceId);if(ws.lifecycleStatus()!=WorkspaceLifecycleStatus.APPROVED)throw new IllegalArgumentException("Workspace must be APPROVED");if(ws.rowVersion()!=rowVersion)throw new com.ftk.tpip.release.domain.exception.WorkspaceConcurrentModificationException(workspaceId,rowVersion);List<WorkspaceAsset> assets=releases.findAssets(workspaceId);if(assets.size()!=1||assets.getFirst().assetType()!=WorkspaceAssetType.BINDING_VERSION)throw new IllegalArgumentException("Workspace must contain exactly one BindingVersion");WorkspaceAsset asset=assets.getFirst();IntegrationBinding binding=bindings.findByCode(AssetCode.of(asset.assetCode())).orElseThrow();IntegrationBindingVersion bv=bindingVersions.findVersion(binding.id(),asset.assetVersionId()).orElseThrow();DeploymentBundleManifest manifest=previews.preview(binding.id(),bv.id(),bundleCode,bundleVersion);ensureVerifiedRoute(workspaceId,manifest);String document=canonicalJson.canonicalString(json.valueToTree(manifest));String artifactChecksum=canonicalJson.sha256(document);String uri="db://tpip-bundle/"+bundleCode+"/"+bundleVersion;String signature="{\"status\":\"UNSIGNED\",\"profile\":\"tpip-bundle-v0.2\"}";DeploymentBundleAsset created=releases.createBundle(new DeploymentBundleAsset(null,bundleCode,bundleVersion,workspaceId,binding.operationId(),bv.id(),ws.environmentCode(),document,uri,artifactChecksum,DefaultBundleCompiler.COMPILER_VERSION,manifest.runtimeCompatibility(),signature,BundleLifecycleStatus.READY,null,null,null),actor(actor));releases.transitionWorkspace(workspaceId,rowVersion,WorkspaceLifecycleStatus.APPROVED,WorkspaceLifecycleStatus.COMPILED,actor(actor));return created;}
 @Transactional(readOnly=true)public List<DeploymentBundleAsset> bundles(long workspaceId){get(workspaceId);return releases.findBundles(workspaceId);}
 @Transactional(readOnly=true)public DeploymentBundleAsset bundle(long id){return releases.findBundle(id).orElseThrow(()->new BundleNotFoundException(Long.toString(id)));}
 @Transactional public DeploymentBundleAsset publish(long id,String actor){DeploymentBundleAsset b=bundle(id);ConfigurationWorkspace ws=get(b.workspaceId());if(ws.lifecycleStatus()!=WorkspaceLifecycleStatus.COMPILED)throw new IllegalArgumentException("Bundle workspace must be COMPILED");return releases.publishBundle(id,actor(actor));}
 @Transactional(readOnly=true)public DeploymentBundleAsset download(String code,String version){DeploymentBundleAsset b=releases.findBundle(code,version).orElseThrow(()->new BundleNotFoundException(code+"@"+version));if(b.lifecycleStatus()!=BundleLifecycleStatus.PUBLISHED)throw new BundleNotFoundException(code+"@"+version);return b;}
 private void ensureVerifiedRoute(long workspaceId,DeploymentBundleManifest manifest){if(manifest.serviceRoutePlan()==null)return;VerificationRun run=releases.findVerifications(workspaceId).stream().filter(v->v.status()==VerificationStatus.PASSED).max(Comparator.comparingLong(VerificationRun::id)).orElseThrow(()->new IllegalArgumentException("Service route requires PASSED verification evidence"));VerificationCheck check=releases.findVerificationChecks(run.id()).stream().filter(c->c.checkCode().equals("BUNDLE_PREVIEW")&&c.status()==VerificationCheckStatus.PASSED).findFirst().orElseThrow(()->new IllegalArgumentException("Service route verification evidence is missing"));try{JsonNode evidence=json.readTree(check.evidenceDocument());long verifiedId=evidence.path("routeVersionId").asLong();String verifiedChecksum=evidence.path("routeContentChecksum").asText();if(verifiedId!=manifest.serviceRoutePlan().routeVersionId()||!verifiedChecksum.equals(manifest.serviceRoutePlan().contentChecksum()))throw new IllegalArgumentException("Published service route changed after verification; verify the Workspace again");}catch(com.fasterxml.jackson.core.JsonProcessingException e){throw new IllegalStateException("Stored route verification evidence is invalid",e);}}
 private ConfigurationWorkspace draft(long id){ConfigurationWorkspace ws=get(id);if(ws.lifecycleStatus()!=WorkspaceLifecycleStatus.DRAFT)throw new com.ftk.tpip.release.domain.exception.WorkspaceLifecycleException(id,"operation requires DRAFT");return ws;}private String object(JsonNode n,String field){if(n==null||n.isNull())return "{}";if(!n.isObject())throw new IllegalArgumentException(field+" must be a JSON object");return canonicalJson.canonicalString(n);}private static boolean approved(List<WorkspaceApproval> a,String stage){return a.stream().anyMatch(x->x.approvalStage().equals(stage)&&x.decision()==ApprovalDecision.APPROVED);}private static String optional(String v,int max){if(v==null||v.isBlank())return null;String x=v.trim();if(x.length()>max)throw new IllegalArgumentException("text is too long");return x;}private static String actor(String v){if(v==null||v.isBlank()||v.trim().length()>100)throw new IllegalArgumentException("actor is blank or too long");return v.trim();}
}
