package com.ftk.tpip.adapters.persistence.jdbc.catalog;
import com.ftk.tpip.catalog.domain.exception.*;import com.ftk.tpip.catalog.domain.model.*;import com.ftk.tpip.catalog.domain.repository.CatalogHierarchyRepository;import com.ftk.tpip.shared.AssetCode;import java.sql.*;import java.util.*;import org.springframework.dao.DuplicateKeyException;import org.springframework.jdbc.core.*;import org.springframework.jdbc.core.namedparam.*;import org.springframework.jdbc.support.GeneratedKeyHolder;
public class JdbcCatalogHierarchyRepository implements CatalogHierarchyRepository{
private static final String DC="id,domain_code,domain_name,description,owner_code,status,row_version,created_at,updated_at";private static final String CC="id,domain_id,capability_code,capability_name,description,owner_code,status,row_version,created_at,updated_at";
private static final RowMapper<BusinessDomain> DM=(r,n)->new BusinessDomain(r.getLong("id"),AssetCode.of(r.getString("domain_code")),r.getString("domain_name"),r.getString("description"),r.getString("owner_code"),CatalogAssetStatus.valueOf(r.getString("status")),r.getLong("row_version"),r.getTimestamp("created_at").toInstant(),r.getTimestamp("updated_at").toInstant());
private static final RowMapper<CanonicalCapability> CM=(r,n)->new CanonicalCapability(r.getLong("id"),r.getLong("domain_id"),AssetCode.of(r.getString("capability_code")),r.getString("capability_name"),r.getString("description"),r.getString("owner_code"),CatalogAssetStatus.valueOf(r.getString("status")),r.getLong("row_version"),r.getTimestamp("created_at").toInstant(),r.getTimestamp("updated_at").toInstant());private final JdbcTemplate j;private final NamedParameterJdbcTemplate n;public JdbcCatalogHierarchyRepository(JdbcTemplate j){this.j=j;this.n=new NamedParameterJdbcTemplate(j);}
public Optional<BusinessDomain> findDomain(long id){return j.query("SELECT "+DC+" FROM tpip_business_domain WHERE id=?",DM,id).stream().findFirst();}public Optional<BusinessDomain> findDomainByCode(AssetCode c){return j.query("SELECT "+DC+" FROM tpip_business_domain WHERE domain_code=?",DM,c.value()).stream().findFirst();}
public List<BusinessDomain> findDomains(String k,CatalogAssetStatus s,int o,int l){var p=parts(false,null,k,s);return n.query("SELECT "+DC+" FROM tpip_business_domain"+p.w+" ORDER BY id DESC LIMIT :l OFFSET :o",p.p.addValue("l",l).addValue("o",o),DM);}public long countDomains(String k,CatalogAssetStatus s){var p=parts(false,null,k,s);Long v=n.queryForObject("SELECT COUNT(*) FROM tpip_business_domain"+p.w,p.p,Long.class);return v==null?0:v;}
public BusinessDomain createDomain(BusinessDomain d,String a){var key=new GeneratedKeyHolder();try{j.update(c->{var x=c.prepareStatement("INSERT INTO tpip_business_domain(domain_code,domain_name,description,owner_code,status,row_version,created_by,updated_by) VALUES(?,?,?,?,?,0,?,?)",Statement.RETURN_GENERATED_KEYS);x.setString(1,d.domainCode().value());x.setString(2,d.domainName());x.setString(3,d.description());x.setString(4,d.ownerCode());x.setString(5,d.status().name());x.setString(6,a);x.setString(7,a);return x;},key);}catch(DuplicateKeyException e){throw new CatalogCodeAlreadyExistsException("Business domain",d.domainCode().value());}var r=findDomain(key.getKey().longValue()).orElseThrow();audit("BUSINESS_DOMAIN_CREATED","BUSINESS_DOMAIN",r.domainCode().value(),a);return r;}
public BusinessDomain updateDomain(BusinessDomain d,String a){int x=j.update("UPDATE tpip_business_domain SET domain_name=?,description=?,owner_code=?,status=?,row_version=row_version+1,updated_by=? WHERE id=? AND row_version=?",d.domainName(),d.description(),d.ownerCode(),d.status().name(),a,d.id(),d.rowVersion());if(x==0)throw new CatalogConcurrentModificationException("Business domain",d.id(),d.rowVersion());var r=findDomain(d.id()).orElseThrow();audit("BUSINESS_DOMAIN_UPDATED","BUSINESS_DOMAIN",r.domainCode().value(),a);return r;}
public Optional<CanonicalCapability> findCapability(long id){return j.query("SELECT "+CC+" FROM tpip_capability WHERE id=?",CM,id).stream().findFirst();}public Optional<CanonicalCapability> findCapabilityByCode(AssetCode c){return j.query("SELECT "+CC+" FROM tpip_capability WHERE capability_code=?",CM,c.value()).stream().findFirst();}
public List<CanonicalCapability> findCapabilities(Long d,String k,CatalogAssetStatus s,int o,int l){var p=parts(true,d,k,s);return n.query("SELECT "+CC+" FROM tpip_capability"+p.w+" ORDER BY id DESC LIMIT :l OFFSET :o",p.p.addValue("l",l).addValue("o",o),CM);}public long countCapabilities(Long d,String k,CatalogAssetStatus s){var p=parts(true,d,k,s);Long v=n.queryForObject("SELECT COUNT(*) FROM tpip_capability"+p.w,p.p,Long.class);return v==null?0:v;}
public CanonicalCapability createCapability(CanonicalCapability c,String a){var key=new GeneratedKeyHolder();try{j.update(z->{var x=z.prepareStatement("INSERT INTO tpip_capability(domain_id,capability_code,capability_name,description,owner_code,status,row_version,created_by,updated_by) VALUES(?,?,?,?,?,?,0,?,?)",Statement.RETURN_GENERATED_KEYS);x.setLong(1,c.domainId());x.setString(2,c.capabilityCode().value());x.setString(3,c.capabilityName());x.setString(4,c.description());x.setString(5,c.ownerCode());x.setString(6,c.status().name());x.setString(7,a);x.setString(8,a);return x;},key);}catch(DuplicateKeyException e){throw new CatalogCodeAlreadyExistsException("Capability",c.capabilityCode().value());}var r=findCapability(key.getKey().longValue()).orElseThrow();audit("CANONICAL_CAPABILITY_CREATED","CANONICAL_CAPABILITY",r.capabilityCode().value(),a);return r;}
public CanonicalCapability updateCapability(CanonicalCapability c,String a){int x=j.update("UPDATE tpip_capability SET capability_name=?,description=?,owner_code=?,status=?,row_version=row_version+1,updated_by=? WHERE id=? AND row_version=?",c.capabilityName(),c.description(),c.ownerCode(),c.status().name(),a,c.id(),c.rowVersion());if(x==0)throw new CatalogConcurrentModificationException("Capability",c.id(),c.rowVersion());var r=findCapability(c.id()).orElseThrow();audit("CANONICAL_CAPABILITY_UPDATED","CANONICAL_CAPABILITY",r.capabilityCode().value(),a);return r;}
private void audit(String e,String t,String c,String a){j.update("INSERT INTO tpip_audit_event(event_id,event_type,actor_type,actor_code,asset_type,asset_code,event_summary) VALUES(UUID(),?,'USER',?,?,?,?)",e,a,t,c,e.replace('_',' '));}private static P parts(boolean capability,Long d,String k,CatalogAssetStatus s){List<String> q=new ArrayList<>();var p=new MapSqlParameterSource();if(d!=null){q.add("domain_id=:d");p.addValue("d",d);}if(k!=null&&!k.isBlank()){q.add(capability?"(capability_code LIKE :k OR capability_name LIKE :k)":"(domain_code LIKE :k OR domain_name LIKE :k)");p.addValue("k","%"+k.trim()+"%");}if(s!=null){q.add("status=:s");p.addValue("s",s.name());}return new P(q.isEmpty()?"":" WHERE "+String.join(" AND ",q),p);}private record P(String w,MapSqlParameterSource p){}
}
