CREATE TABLE tpip_notification_attempt_archive_batch (
    id                  BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    batch_code          CHAR(36) NOT NULL,
    environment_code    VARCHAR(32) NOT NULL,
    window_start        DATETIME(3) NOT NULL,
    window_end          DATETIME(3) NOT NULL,
    first_attempt_id    BIGINT UNSIGNED NOT NULL,
    last_attempt_id     BIGINT UNSIGNED NOT NULL,
    record_count        BIGINT UNSIGNED NOT NULL,
    artifact_uri        VARCHAR(1000) NULL,
    artifact_checksum   CHAR(64) NULL,
    artifact_size_bytes BIGINT UNSIGNED NULL,
    manifest_document   JSON NULL,
    manifest_checksum   CHAR(64) NULL,
    archive_status      VARCHAR(20) NOT NULL DEFAULT 'CREATED',
    legal_hold          BOOLEAN NOT NULL DEFAULT FALSE,
    hold_reason         VARCHAR(500) NULL,
    held_by             VARCHAR(100) NULL,
    held_at             DATETIME(3) NULL,
    verified_by         VARCHAR(100) NULL,
    verified_at         DATETIME(3) NULL,
    purged_by           VARCHAR(100) NULL,
    purged_at           DATETIME(3) NULL,
    purged_record_count BIGINT UNSIGNED NULL,
    failure_reason      VARCHAR(500) NULL,
    created_by          VARCHAR(100) NOT NULL,
    created_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    CONSTRAINT uk_notification_attempt_archive_code UNIQUE (batch_code),
    CONSTRAINT uk_notification_attempt_archive_window UNIQUE (environment_code, window_start, window_end),
    CONSTRAINT chk_notification_attempt_archive_window CHECK (window_end > window_start),
    CONSTRAINT chk_notification_attempt_archive_ids CHECK (last_attempt_id >= first_attempt_id),
    CONSTRAINT chk_notification_attempt_archive_status CHECK (
        archive_status IN ('CREATED', 'STORED', 'VERIFIED', 'PURGED', 'FAILED')),
    KEY idx_notification_attempt_archive_environment_time (environment_code, window_end, archive_status)
);
