CREATE TABLE tpip_access_channel (
    id                  BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    provider_id         BIGINT UNSIGNED NOT NULL,
    channel_code        VARCHAR(180) NOT NULL,
    channel_name        VARCHAR(200) NOT NULL,
    base_url            VARCHAR(500) NOT NULL,
    credential_ref_id   BIGINT UNSIGNED NULL,
    description         VARCHAR(1000) NULL,
    status              VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    row_version         BIGINT UNSIGNED NOT NULL DEFAULT 0,
    created_by          VARCHAR(100) NOT NULL,
    created_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_by          VARCHAR(100) NOT NULL,
    updated_at          DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_access_channel_code (channel_code),
    KEY idx_access_channel_provider (provider_id, status),
    KEY idx_access_channel_credential (credential_ref_id),
    CONSTRAINT fk_access_channel_provider FOREIGN KEY (provider_id) REFERENCES tpip_provider (id),
    CONSTRAINT fk_access_channel_credential FOREIGN KEY (credential_ref_id) REFERENCES tpip_credential_ref (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE tpip_access_channel_interface (
    id                      BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    channel_id              BIGINT UNSIGNED NOT NULL,
    provider_contract_id    BIGINT UNSIGNED NOT NULL,
    created_by              VARCHAR(100) NOT NULL,
    created_at              DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_channel_interface (channel_id, provider_contract_id),
    KEY idx_channel_interface_contract (provider_contract_id),
    CONSTRAINT fk_channel_interface_channel FOREIGN KEY (channel_id) REFERENCES tpip_access_channel (id),
    CONSTRAINT fk_channel_interface_contract FOREIGN KEY (provider_contract_id) REFERENCES tpip_provider_contract (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE tpip_access_parameter (
    id                      BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    channel_id              BIGINT UNSIGNED NOT NULL,
    scope_type              VARCHAR(32) NOT NULL,
    scope_key               VARCHAR(200) NOT NULL,
    provider_contract_id    BIGINT UNSIGNED NULL,
    parameter_code          VARCHAR(180) NOT NULL,
    parameter_name          VARCHAR(200) NOT NULL,
    parameter_location      VARCHAR(32) NOT NULL,
    source_type             VARCHAR(32) NOT NULL,
    data_type               VARCHAR(32) NOT NULL,
    value_document          JSON NULL,
    source_selector         VARCHAR(500) NULL,
    secret_ref_id           BIGINT UNSIGNED NULL,
    override_mode           VARCHAR(32) NOT NULL DEFAULT 'REPLACE',
    required_flag           BOOLEAN NOT NULL DEFAULT FALSE,
    sensitive_flag          BOOLEAN NOT NULL DEFAULT FALSE,
    caller_overridable      BOOLEAN NOT NULL DEFAULT FALSE,
    description             VARCHAR(1000) NULL,
    row_version             BIGINT UNSIGNED NOT NULL DEFAULT 0,
    created_by              VARCHAR(100) NOT NULL,
    created_at              DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_by              VARCHAR(100) NOT NULL,
    updated_at              DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_access_parameter (channel_id, scope_type, scope_key, parameter_location, parameter_code),
    KEY idx_access_parameter_contract (provider_contract_id),
    KEY idx_access_parameter_secret (secret_ref_id),
    CONSTRAINT fk_access_parameter_channel FOREIGN KEY (channel_id) REFERENCES tpip_access_channel (id),
    CONSTRAINT fk_access_parameter_contract FOREIGN KEY (provider_contract_id) REFERENCES tpip_provider_contract (id),
    CONSTRAINT fk_access_parameter_secret FOREIGN KEY (secret_ref_id) REFERENCES tpip_credential_ref (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
