CREATE TABLE tpip_channel_auth_config_version (
    id                       BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    channel_id               BIGINT UNSIGNED NOT NULL,
    version_no               INT UNSIGNED NOT NULL,
    auth_template_version_id BIGINT UNSIGNED NOT NULL,
    credential_profile_id    BIGINT UNSIGNED NOT NULL,
    configuration_document   JSON NOT NULL,
    compiled_policy_document JSON NOT NULL,
    compiler_version         VARCHAR(100) NOT NULL,
    content_checksum         CHAR(64) NOT NULL,
    lifecycle_status         VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
    published_at             DATETIME(3) NULL,
    created_by               VARCHAR(100) NOT NULL,
    created_at               DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_channel_auth_config_version (channel_id, version_no),
    KEY idx_channel_auth_config_effective (channel_id, lifecycle_status, version_no),
    KEY idx_channel_auth_config_template (auth_template_version_id),
    KEY idx_channel_auth_config_profile (credential_profile_id),
    CONSTRAINT fk_channel_auth_config_channel FOREIGN KEY (channel_id) REFERENCES tpip_access_channel (id),
    CONSTRAINT fk_channel_auth_config_template FOREIGN KEY (auth_template_version_id) REFERENCES tpip_auth_template_version (id),
    CONSTRAINT fk_channel_auth_config_profile FOREIGN KEY (credential_profile_id) REFERENCES tpip_credential_profile (id),
    CONSTRAINT chk_channel_auth_config_status CHECK (lifecycle_status IN ('DRAFT','PUBLISHED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
