CREATE TABLE tpip_mcp_tool (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    operation_id BIGINT UNSIGNED NOT NULL,
    tool_name VARCHAR(64) NOT NULL,
    display_name VARCHAR(200) NOT NULL,
    description VARCHAR(1000) NOT NULL,
    owner_code VARCHAR(100) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    row_version BIGINT UNSIGNED NOT NULL DEFAULT 0,
    created_by VARCHAR(100) NOT NULL,
    updated_by VARCHAR(100) NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_mcp_tool_name (tool_name),
    KEY idx_mcp_tool_operation (operation_id,status),
    KEY idx_mcp_tool_status (status),
    CONSTRAINT fk_mcp_tool_operation FOREIGN KEY (operation_id) REFERENCES tpip_canonical_operation(id),
    CONSTRAINT chk_mcp_tool_status CHECK (status IN ('ACTIVE','INACTIVE'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE tpip_mcp_tool_version (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tool_id BIGINT UNSIGNED NOT NULL,
    version_no INT UNSIGNED NOT NULL,
    title VARCHAR(200) NOT NULL,
    description VARCHAR(2000) NOT NULL,
    fixed_scenario VARCHAR(100) NULL,
    input_schema JSON NOT NULL,
    output_schema JSON NULL,
    read_only_hint BOOLEAN NOT NULL DEFAULT FALSE,
    destructive_hint BOOLEAN NOT NULL DEFAULT FALSE,
    idempotent_hint BOOLEAN NOT NULL DEFAULT FALSE,
    open_world_hint BOOLEAN NOT NULL DEFAULT TRUE,
    confirmation_mode VARCHAR(20) NOT NULL DEFAULT 'NONE',
    content_checksum CHAR(64) NOT NULL,
    lifecycle_status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    published_by VARCHAR(100) NULL,
    published_at DATETIME(3) NULL,
    created_by VARCHAR(100) NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_mcp_tool_version (tool_id,version_no),
    UNIQUE KEY uk_mcp_tool_checksum (tool_id,content_checksum),
    KEY idx_mcp_tool_version_status (tool_id,lifecycle_status,version_no),
    CONSTRAINT fk_mcp_tool_version_tool FOREIGN KEY (tool_id) REFERENCES tpip_mcp_tool(id),
    CONSTRAINT chk_mcp_tool_version_status CHECK (lifecycle_status IN ('DRAFT','PUBLISHED')),
    CONSTRAINT chk_mcp_tool_confirmation CHECK (confirmation_mode IN ('NONE','REQUIRED','ALWAYS'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
