package com.ftk.tpip.adapters.persistence.jdbc.release;

import com.ftk.tpip.release.domain.exception.*;
import com.ftk.tpip.release.domain.model.*;
import com.ftk.tpip.release.domain.repository.ReleaseRepository;
import com.ftk.tpip.shared.AssetCode;
import java.sql.*;import java.util.*;
import org.springframework.dao.DuplicateKeyException;
import org.springframework.jdbc.core.*;
import org.springframework.jdbc.support.GeneratedKeyHolder;

public class JdbcReleaseRepository implements ReleaseRepository{
 private static final String W="id,workspace_code,workspace_name,base_bundle_id,environment_code,lifecycle_status,risk_level,owner_code,row_version,created_at,updated_at";
 private static final RowMapper<ConfigurationWorkspace> WM=(r,n)->new ConfigurationWorkspace(r.getLong("id"),AssetCode.of(r.getString("workspace_code")),r.getString("workspace_name"),nullable(r,"base_bundle_id"),r.getString("environment_code"),WorkspaceLifecycleStatus.valueOf(r.getString("lifecycle_status")),WorkspaceRiskLevel.valueOf(r.getString("risk_level")),r.getString("owner_code"),r.getLong("row_version"),r.getTimestamp("created_at").toInstant(),r.getTimestamp("updated_at").toInstant());
 private static final RowMapper<WorkspaceAsset> AM=(r,n)->new WorkspaceAsset(r.getLong("id"),r.getLong("workspace_id"),WorkspaceAssetType.valueOf(r.getString("asset_type")),r.getString("asset_code"),r.getLong("asset_version_id"),WorkspaceChangeType.valueOf(r.getString("change_type")),r.getString("dependency_metadata"),r.getTimestamp("created_at").toInstant());
 private static final RowMapper<VerificationRun> VM=(r,n)->{Timestamp f=r.getTimestamp("finished_at");return new VerificationRun(r.getLong("id"),r.getLong("workspace_id"),r.getLong("run_no"),VerificationRunType.valueOf(r.getString("run_type")),VerificationStatus.valueOf(r.getString("status")),r.getInt("total_count"),r.getInt("passed_count"),r.getInt("failed_count"),r.getString("evidence_uri"),r.getString("result_summary"),r.getTimestamp("started_at").toInstant(),f==null?null:f.toInstant());};
 private static final RowMapper<VerificationCheck> VCM=(r,n)->new VerificationCheck(r.getLong("id"),r.getLong("verification_run_id"),r.getString("check_code"),r.getString("check_name"),VerificationCheckStatus.valueOf(r.getString("status")),r.getString("result_details"),r.getString("evidence_document"),r.getTimestamp("started_at").toInstant(),r.getTimestamp("finished_at").toInstant());
 private static final RowMapper<WorkspaceApproval> APM=(r,n)->new WorkspaceApproval(r.getLong("id"),r.getLong("workspace_id"),r.getString("approval_stage"),r.getString("approver_code"),ApprovalDecision.valueOf(r.getString("decision")),r.getString("decision_comment"),r.getString("evidence_snapshot"),r.getTimestamp("decided_at").toInstant());
 private static final String B="id,bundle_code,bundle_version,workspace_id,operation_id,binding_version_id,environment_code,manifest_document,artifact_uri,artifact_checksum,compiler_version,runtime_compatibility,signature_metadata,lifecycle_status,published_by,published_at,created_at";
 private static final RowMapper<DeploymentBundleAsset> BM=(r,n)->{Timestamp p=r.getTimestamp("published_at");return new DeploymentBundleAsset(r.getLong("id"),r.getString("bundle_code"),r.getString("bundle_version"),r.getLong("workspace_id"),r.getLong("operation_id"),r.getLong("binding_version_id"),r.getString("environment_code"),r.getString("manifest_document"),r.getString("artifact_uri"),r.getString("artifact_checksum"),r.getString("compiler_version"),r.getString("runtime_compatibility"),r.getString("signature_metadata"),BundleLifecycleStatus.valueOf(r.getString("lifecycle_status")),r.getString("published_by"),p==null?null:p.toInstant(),r.getTimestamp("created_at").toInstant());};
 private final JdbcTemplate j;public JdbcReleaseRepository(JdbcTemplate j){this.j=j;}
 public Optional<ConfigurationWorkspace> findWorkspace(long id){return j.query("SELECT "+W+" FROM tpip_workspace WHERE id=?",WM,id).stream().findFirst();}
 public Optional<ConfigurationWorkspace> findWorkspaceByCode(AssetCode code){return j.query("SELECT "+W+" FROM tpip_workspace WHERE workspace_code=?",WM,code.value()).stream().findFirst();}
 public List<ConfigurationWorkspace> findWorkspaces(){return j.query("SELECT "+W+" FROM tpip_workspace ORDER BY id DESC",WM);}
 public ConfigurationWorkspace createWorkspace(ConfigurationWorkspace w,String actor){var k=new GeneratedKeyHolder();try{j.update(c->{var s=c.prepareStatement("INSERT INTO tpip_workspace(workspace_code,workspace_name,base_bundle_id,environment_code,lifecycle_status,risk_level,owner_code,row_version,created_by,updated_by) VALUES(?,?,?,?,'DRAFT',?,?,0,?,?)",Statement.RETURN_GENERATED_KEYS);s.setString(1,w.workspaceCode().value());s.setString(2,w.workspaceName());set(s,3,w.baseBundleId());s.setString(4,w.environmentCode());s.setString(5,w.riskLevel().name());s.setString(6,w.ownerCode());s.setString(7,actor);s.setString(8,actor);return s;},k);}catch(DuplicateKeyException e){throw new WorkspaceAlreadyExistsException(w.workspaceCode().value());}if(k.getKey()==null)throw new IllegalStateException("MySQL did not return workspace id");var x=findWorkspace(k.getKey().longValue()).orElseThrow();audit("WORKSPACE_CREATED","CONFIGURATION_WORKSPACE",x.workspaceCode().value(),null,actor,"Created configuration workspace");return x;}
 public ConfigurationWorkspace transitionWorkspace(long id,long version,WorkspaceLifecycleStatus expected,WorkspaceLifecycleStatus target,String actor){int n=j.update("UPDATE tpip_workspace SET lifecycle_status=?,row_version=row_version+1,updated_by=? WHERE id=? AND row_version=? AND lifecycle_status=?",target.name(),actor,id,version,expected.name());if(n==0){var current=findWorkspace(id).orElseThrow();if(current.rowVersion()!=version)throw new WorkspaceConcurrentModificationException(id,version);throw new WorkspaceLifecycleException(id,"expected "+expected+" but was "+current.lifecycleStatus());}var x=findWorkspace(id).orElseThrow();audit("WORKSPACE_"+target.name(),"CONFIGURATION_WORKSPACE",x.workspaceCode().value(),null,actor,"Transitioned workspace to "+target);return x;}
 public WorkspaceAsset addAsset(WorkspaceAsset a,String actor){var k=new GeneratedKeyHolder();try{j.update(c->{var s=c.prepareStatement("INSERT INTO tpip_workspace_asset(workspace_id,asset_type,asset_code,asset_version_id,change_type,dependency_metadata,created_by) VALUES(?,?,?,?,?,?,?)",Statement.RETURN_GENERATED_KEYS);s.setLong(1,a.workspaceId());s.setString(2,a.assetType().name());s.setString(3,a.assetCode());s.setLong(4,a.assetVersionId());s.setString(5,a.changeType().name());s.setString(6,a.dependencyMetadata());s.setString(7,actor);return s;},k);}catch(DuplicateKeyException e){throw new IllegalArgumentException("Workspace already contains asset: "+a.assetCode());}if(k.getKey()==null)throw new IllegalStateException("MySQL did not return workspace asset id");var x=j.query("SELECT id,workspace_id,asset_type,asset_code,asset_version_id,change_type,dependency_metadata,created_at FROM tpip_workspace_asset WHERE id=?",AM,k.getKey().longValue()).getFirst();audit("WORKSPACE_ASSET_ADDED","CONFIGURATION_WORKSPACE",Long.toString(a.workspaceId()),null,actor,"Added "+a.assetCode());return x;}
 public List<WorkspaceAsset> findAssets(long id){return j.query("SELECT id,workspace_id,asset_type,asset_code,asset_version_id,change_type,dependency_metadata,created_at FROM tpip_workspace_asset WHERE workspace_id=? ORDER BY id",AM,id);}
 public VerificationRun startVerification(long id,VerificationRunType type,long fixtureSuiteVersionId,String actor){if(fixtureSuiteVersionId<=0)throw new IllegalArgumentException("fixtureSuiteVersionId must be positive");Long no=j.queryForObject("SELECT COALESCE(MAX(run_no),0)+1 FROM tpip_verification_run WHERE workspace_id=?",Long.class,id);var k=new GeneratedKeyHolder();try{j.update(c->{var s=c.prepareStatement("INSERT INTO tpip_verification_run(workspace_id,run_no,run_type,status,total_count,passed_count,failed_count,result_summary,started_at,created_by) VALUES(?,?,?,'RUNNING',0,0,0,?,CURRENT_TIMESTAMP(3),?)",Statement.RETURN_GENERATED_KEYS);s.setLong(1,id);s.setLong(2,no==null?1:no);s.setString(3,type.name());s.setString(4,"{\"fixtureSuiteVersionId\":"+fixtureSuiteVersionId+",\"serverExecuted\":true}");s.setString(5,actor);return s;},k);}catch(DuplicateKeyException e){throw new IllegalArgumentException("Workspace already has an active verification or concurrent run number: "+id);}if(k.getKey()==null)throw new IllegalStateException("MySQL did not return verification run id");var x=findVerification(k.getKey().longValue()).orElseThrow();audit("WORKSPACE_VERIFICATION_STARTED","CONFIGURATION_WORKSPACE",Long.toString(id),Long.toString(x.runNo()),actor,"Started server-side verification");return x;}
 public VerificationRun completeVerification(long runId,VerificationStatus status,int total,int passed,int failed,String evidence,String summary,String actor){if(status==VerificationStatus.RUNNING)throw new IllegalArgumentException("completion status must be PASSED or FAILED");int n=j.update("UPDATE tpip_verification_run SET status=?,total_count=?,passed_count=?,failed_count=?,evidence_uri=?,result_summary=?,finished_at=CURRENT_TIMESTAMP(3) WHERE id=? AND status='RUNNING'",status.name(),total,passed,failed,evidence,summary,runId);if(n==0)throw new IllegalArgumentException("verification run is not RUNNING: "+runId);var x=findVerification(runId).orElseThrow();audit("WORKSPACE_VERIFICATION_"+status.name(),"CONFIGURATION_WORKSPACE",Long.toString(x.workspaceId()),Long.toString(x.runNo()),actor,"Completed server-side verification as "+status);return x;}
 public Optional<VerificationRun> findVerification(long id){return j.query("SELECT id,workspace_id,run_no,run_type,status,total_count,passed_count,failed_count,evidence_uri,result_summary,started_at,finished_at FROM tpip_verification_run WHERE id=?",VM,id).stream().findFirst();}
 public List<VerificationRun> findVerifications(long id){return j.query("SELECT id,workspace_id,run_no,run_type,status,total_count,passed_count,failed_count,evidence_uri,result_summary,started_at,finished_at FROM tpip_verification_run WHERE workspace_id=? ORDER BY run_no DESC",VM,id);}
 public List<VerificationRun> findRunningVerificationsStartedBefore(java.time.Instant cutoff,int limit){if(limit<1||limit>1000)throw new IllegalArgumentException("limit must be between 1 and 1000");return j.query("SELECT id,workspace_id,run_no,run_type,status,total_count,passed_count,failed_count,evidence_uri,result_summary,started_at,finished_at FROM tpip_verification_run WHERE status='RUNNING' AND started_at<? ORDER BY started_at,id LIMIT ?",VM,Timestamp.from(cutoff),limit);}
 public VerificationCheck recordVerificationCheck(VerificationCheck check,String actor){var k=new GeneratedKeyHolder();int n=j.update(c->{var s=c.prepareStatement("INSERT INTO tpip_verification_check(verification_run_id,check_code,check_name,status,result_details,evidence_document,started_at,finished_at,created_by) SELECT ?,?,?,?,?,?,?,?,? FROM tpip_verification_run WHERE id=? AND status='RUNNING'",Statement.RETURN_GENERATED_KEYS);s.setLong(1,check.verificationRunId());s.setString(2,check.checkCode());s.setString(3,check.checkName());s.setString(4,check.status().name());s.setString(5,check.resultDetails());s.setString(6,check.evidenceDocument());s.setTimestamp(7,Timestamp.from(check.startedAt()));s.setTimestamp(8,Timestamp.from(check.finishedAt()));s.setString(9,actor);s.setLong(10,check.verificationRunId());return s;},k);if(n==0)throw new IllegalArgumentException("verification run is not RUNNING: "+check.verificationRunId());if(k.getKey()==null)throw new IllegalStateException("MySQL did not return verification check id");return j.query("SELECT id,verification_run_id,check_code,check_name,status,result_details,evidence_document,started_at,finished_at FROM tpip_verification_check WHERE id=?",VCM,k.getKey().longValue()).getFirst();}
 public List<VerificationCheck> findVerificationChecks(long runId){return j.query("SELECT id,verification_run_id,check_code,check_name,status,result_details,evidence_document,started_at,finished_at FROM tpip_verification_check WHERE verification_run_id=? ORDER BY id",VCM,runId);}
 public WorkspaceApproval recordApproval(WorkspaceApproval a){var k=new GeneratedKeyHolder();j.update(c->{var s=c.prepareStatement("INSERT INTO tpip_approval(workspace_id,approval_stage,approver_code,decision,decision_comment,evidence_snapshot) VALUES(?,?,?,?,?,?)",Statement.RETURN_GENERATED_KEYS);s.setLong(1,a.workspaceId());s.setString(2,a.approvalStage());s.setString(3,a.approverCode());s.setString(4,a.decision().name());s.setString(5,a.decisionComment());s.setString(6,a.evidenceSnapshot());return s;},k);var x=j.query("SELECT id,workspace_id,approval_stage,approver_code,decision,decision_comment,evidence_snapshot,decided_at FROM tpip_approval WHERE id=?",APM,k.getKey().longValue()).getFirst();audit("WORKSPACE_"+a.decision().name(),"CONFIGURATION_WORKSPACE",Long.toString(a.workspaceId()),a.approvalStage(),a.approverCode(),"Recorded workspace approval decision");return x;}
 public List<WorkspaceApproval> findApprovals(long id){return j.query("SELECT id,workspace_id,approval_stage,approver_code,decision,decision_comment,evidence_snapshot,decided_at FROM tpip_approval WHERE workspace_id=? ORDER BY id DESC",APM,id);}
 public Optional<DeploymentBundleAsset> findBundle(long id){return j.query("SELECT "+B+" FROM tpip_bundle WHERE id=?",BM,id).stream().findFirst();}public Optional<DeploymentBundleAsset> findBundle(String code,String version){return j.query("SELECT "+B+" FROM tpip_bundle WHERE bundle_code=? AND bundle_version=?",BM,code,version).stream().findFirst();}public List<DeploymentBundleAsset> findBundles(long ws){return j.query("SELECT "+B+" FROM tpip_bundle WHERE workspace_id=? ORDER BY id DESC",BM,ws);}
 public DeploymentBundleAsset createBundle(DeploymentBundleAsset b,String actor){var k=new GeneratedKeyHolder();try{j.update(c->{var s=c.prepareStatement("INSERT INTO tpip_bundle(bundle_code,bundle_version,workspace_id,operation_id,binding_version_id,environment_code,manifest_document,artifact_uri,artifact_checksum,compiler_version,runtime_compatibility,signature_metadata,lifecycle_status,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?, 'READY',?)",Statement.RETURN_GENERATED_KEYS);s.setString(1,b.bundleCode());s.setString(2,b.bundleVersion());s.setLong(3,b.workspaceId());s.setLong(4,b.operationId());s.setLong(5,b.bindingVersionId());s.setString(6,b.environmentCode());s.setString(7,b.manifestDocument());s.setString(8,b.artifactUri());s.setString(9,b.artifactChecksum());s.setString(10,b.compilerVersion());s.setString(11,b.runtimeCompatibility());s.setString(12,b.signatureMetadata());s.setString(13,actor);return s;},k);}catch(DuplicateKeyException e){throw new BundleAlreadyExistsException(b.bundleCode(),b.bundleVersion());}if(k.getKey()==null)throw new IllegalStateException("MySQL did not return bundle id");var x=findBundle(k.getKey().longValue()).orElseThrow();audit("BUNDLE_CREATED","DEPLOYMENT_BUNDLE",x.bundleCode(),x.bundleVersion(),actor,"Created immutable deployment bundle");return x;}
 public DeploymentBundleAsset publishBundle(long id,String actor){int n=j.update("UPDATE tpip_bundle SET lifecycle_status='PUBLISHED',published_by=?,published_at=CURRENT_TIMESTAMP(3) WHERE id=? AND lifecycle_status='READY'",actor,id);if(n==0)throw new BundleLifecycleException(id,"only a READY bundle can be published");var x=findBundle(id).orElseThrow();audit("BUNDLE_PUBLISHED","DEPLOYMENT_BUNDLE",x.bundleCode(),x.bundleVersion(),actor,"Published deployment bundle");return x;}
 private void audit(String type,String assetType,String code,String version,String actor,String summary){j.update("INSERT INTO tpip_audit_event(event_id,event_type,actor_type,actor_code,asset_type,asset_code,asset_version,event_summary) VALUES(UUID(),?,'USER',?,?,?,?,?)",type,actor,assetType,code,version,summary);}private static Long nullable(ResultSet r,String c)throws SQLException{long v=r.getLong(c);return r.wasNull()?null:v;}private static void set(PreparedStatement s,int i,Long v)throws SQLException{if(v==null)s.setNull(i,Types.BIGINT);else s.setLong(i,v);}
}
