package com.ftk.tpip.runtime;

public enum BundleResolutionCode {
    REFERENCE_NOT_FOUND,
    SOURCE_UNAVAILABLE,
    ARTIFACT_TOO_LARGE,
    ARTIFACT_CHECKSUM_MISSING,
    ARTIFACT_CHECKSUM_MISMATCH,
    MANIFEST_INVALID,
    MANIFEST_IDENTITY_MISMATCH,
    CONTENT_CHECKSUM_MISMATCH,
    RUNTIME_INCOMPATIBLE,
    LAST_KNOWN_GOOD_EXPIRED
}
