package com.ftk.tpip.runtime;

public enum RuntimeExecutionCode {
    DEADLINE_EXCEEDED,
    CANONICAL_REQUEST_INVALID,
    ROUTE_NO_CANDIDATE,
    REQUEST_MAPPING_FAILED,
    PROVIDER_REQUEST_INVALID,
    POLICY_EXECUTION_FAILED,
    TRANSPORT_FAILED,
    PROVIDER_HTTP_ERROR,
    PROVIDER_RESPONSE_INVALID,
    RESPONSE_MAPPING_FAILED,
    CANONICAL_RESPONSE_INVALID,
    PIPELINE_FAILED
}
