package com.ftk.tpip.runtime;

public enum RuntimeStage {
    CANONICAL_REQUEST_VALIDATION,
    SERVICE_ROUTE_SELECTION,
    BEFORE_REQUEST_MAPPING_POLICY,
    REQUEST_MAPPING,
    AFTER_REQUEST_MAPPING_POLICY,
    ACCESS_PARAMETER_ASSEMBLY,
    PROVIDER_REQUEST_VALIDATION,
    BEFORE_TRANSPORT_POLICY,
    TRANSPORT,
    ON_PROVIDER_ERROR_POLICY,
    AFTER_TRANSPORT_POLICY,
    PROVIDER_RESPONSE_VALIDATION,
    BEFORE_RESPONSE_MAPPING_POLICY,
    RESPONSE_MAPPING,
    AFTER_RESPONSE_MAPPING_POLICY,
    CANONICAL_RESPONSE_VALIDATION,
    ON_PLATFORM_ERROR_POLICY
}
