package com.ftk.tpip.integration.domain.model;

public enum PolicyMountStage { BEFORE_REQUEST_MAPPING, AFTER_REQUEST_MAPPING, BEFORE_TRANSPORT,
    AFTER_TRANSPORT, BEFORE_RESPONSE_MAPPING, AFTER_RESPONSE_MAPPING, ON_PROVIDER_ERROR, ON_PLATFORM_ERROR }
