<script setup lang="ts">
import { computed, reactive, ref } from 'vue'
import { useQuery, useQueryClient } from '@tanstack/vue-query'
import { ElMessage } from 'element-plus'
import { consumerAccessApi, type ConsumerApplication, type ConsumerApplicationDetail } from '../api/consumerAccessApi'
import { accessServiceApi } from '../api/accessServiceApi'

const client=useQueryClient()
const projectsQuery=useQuery({queryKey:['consumer-projects'],queryFn:({signal})=>consumerAccessApi.projects(signal)})
const applicationsQuery=useQuery({queryKey:['consumer-applications'],queryFn:({signal})=>consumerAccessApi.applications(undefined,signal)})
const servicesQuery=useQuery({queryKey:['product-services'],queryFn:({signal})=>accessServiceApi.list(signal)})
const selectedProjectId=ref<number|undefined>()
const selectedApp=ref<ConsumerApplicationDetail|null>(null)
const projectDialog=ref(false),appDialog=ref(false),credentialDialog=ref(false),grantDialog=ref(false),saving=ref(false)
const error=ref('')
const projectForm=reactive({projectCode:'',projectName:'',ownerCode:'local',description:''})
const appForm=reactive({appCode:'',appName:'',ownerCode:'local',description:''})
const credentialForm=reactive({secretReference:'',validUntil:''})
const grantForm=reactive({operationId:undefined as number|undefined,ownerCode:'local',validUntil:'',qpsLimit:undefined as number|undefined,allowedScenarios:''})
const projects=computed(()=>projectsQuery.data.value??[])
const applications=computed(()=>(applicationsQuery.data.value??[]).filter(item=>!selectedProjectId.value||item.projectId===selectedProjectId.value))
function code(value:{value:string}|string):string{return typeof value==='string'?value:value.value}
function dateValue(value:string):string|null{return value?new Date(value).toISOString():null}
async function reload():Promise<void>{await Promise.all([client.invalidateQueries({queryKey:['consumer-projects']}),client.invalidateQueries({queryKey:['consumer-applications']})])}
async function openApp(value:unknown):Promise<void>{selectedApp.value=await consumerAccessApi.application((value as ConsumerApplication).id)}
async function refreshDetail():Promise<void>{if(selectedApp.value)selectedApp.value=await consumerAccessApi.application(selectedApp.value.application.id)}
async function execute(task:()=>Promise<unknown>,message:string):Promise<void>{saving.value=true;error.value='';try{await task();await reload();await refreshDetail();ElMessage.success(message)}catch(e){error.value=e instanceof Error?e.message:'操作失败'}finally{saving.value=false}}
async function createProject():Promise<void>{await execute(async()=>{await consumerAccessApi.createProject({projectCode:projectForm.projectCode.trim(),projectName:projectForm.projectName.trim(),ownerCode:projectForm.ownerCode.trim(),description:projectForm.description.trim()||null});projectDialog.value=false},'调用方项目已创建')}
async function createApplication():Promise<void>{if(!selectedProjectId.value){error.value='请先选择调用方项目';return}await execute(async()=>{await consumerAccessApi.createApplication(selectedProjectId.value!,{appCode:appForm.appCode.trim(),appName:appForm.appName.trim(),ownerCode:appForm.ownerCode.trim(),description:appForm.description.trim()||null});appDialog.value=false},'调用方应用已创建')}
async function createCredential():Promise<void>{if(!selectedApp.value)return;await execute(async()=>{await consumerAccessApi.createCredential(selectedApp.value!.application.id,{secretReference:credentialForm.secretReference.trim(),validFrom:null,validUntil:dateValue(credentialForm.validUntil)});credentialDialog.value=false},'调用凭据草稿已创建')}
async function publishCredential(id:number):Promise<void>{if(!selectedApp.value)return;await execute(()=>consumerAccessApi.publishCredential(selectedApp.value!.application.id,id),'调用凭据已发布')}
async function revokeCredential(id:number):Promise<void>{if(!selectedApp.value)return;await execute(()=>consumerAccessApi.revokeCredential(selectedApp.value!.application.id,id),'调用凭据已撤销')}
async function createGrant():Promise<void>{if(!selectedApp.value||!grantForm.operationId)return;await execute(async()=>{await consumerAccessApi.createGrant(selectedApp.value!.application.id,{operationId:grantForm.operationId!,ownerCode:grantForm.ownerCode.trim(),validFrom:null,validUntil:dateValue(grantForm.validUntil),qpsLimit:grantForm.qpsLimit??null,burstLimit:grantForm.qpsLimit??null,dailyQuota:null,allowedCidrs:[],allowedScenarios:grantForm.allowedScenarios.split(',').map(v=>v.trim()).filter(Boolean)});grantDialog.value=false},'服务授权草稿已创建')}
async function publishGrant(grantId:number,id:number):Promise<void>{await execute(()=>consumerAccessApi.publishGrant(grantId,id),'服务授权已发布，Runtime授权快照将自动刷新')}
</script>

<template><section>
  <div class="product-page-heading"><div><span class="eyebrow">服务消费治理</span><h2>调用方管理</h2><p>识别哪些项目和应用正在使用平台，并明确授权它们可以调用哪些业务服务。</p></div><el-button type="primary" @click="projectDialog=true">＋ 新增调用方项目</el-button></div>
  <el-alert type="info" :closable="false" show-icon title="业务调用编码不是密码。应用必须拥有已发布凭据和对应服务授权，Runtime才会接受调用。" />
  <div class="consumer-layout">
    <aside class="surface consumer-projects"><div class="consumer-section-title"><strong>调用方项目</strong><button @click="selectedProjectId=undefined">全部</button></div><button v-for="item in projects" :key="item.id" :class="{active:selectedProjectId===item.id}" @click="selectedProjectId=item.id"><strong>{{item.projectName}}</strong><small>{{code(item.projectCode)}} · {{item.ownerCode}}</small></button></aside>
    <main class="surface product-table-card"><div class="asset-toolbar"><div><strong>调用方应用</strong><span>每个实际部署单元使用独立身份和凭据。</span></div><el-button type="primary" :disabled="!selectedProjectId" @click="appDialog=true">＋ 新增应用</el-button></div><el-empty v-if="!applications.length" description="当前项目还没有调用方应用"/><el-table v-else :data="applications"><el-table-column prop="appName" label="应用名称"/><el-table-column label="应用编码"><template #default="{row}"><code>{{code(row.appCode)}}</code></template></el-table-column><el-table-column label="状态" width="100"><template #default="{row}">{{row.status==='ACTIVE'?'已启用':'已停用'}}</template></el-table-column><el-table-column label="操作" width="120"><template #default="{row}"><el-button link type="primary" @click="openApp(row)">凭据与授权</el-button></template></el-table-column></el-table></main>
  </div>
  <el-drawer :model-value="selectedApp!==null" title="调用方应用详情" size="850px" @close="selectedApp=null"><template v-if="selectedApp"><div class="consumer-app-hero"><span>应用身份</span><strong>{{selectedApp.application.appName}}</strong><code>{{code(selectedApp.application.appCode)}}</code></div><div class="drawer-section"><div class="asset-toolbar"><div><strong>调用凭据</strong><span>appKey用于标识身份，appSecret只保存环境变量Secret引用。</span></div><el-button type="primary" @click="credentialDialog=true">＋ 新建凭据版本</el-button></div><el-empty v-if="!selectedApp.credentials.length" description="尚未创建调用凭据"/><el-table v-else :data="selectedApp.credentials" size="small"><el-table-column prop="versionNo" label="版本" width="70"/><el-table-column prop="appKey" label="App Key" min-width="230"/><el-table-column prop="secretReference" label="Secret引用" min-width="220"/><el-table-column label="状态" width="100"><template #default="{row}">{{row.lifecycleStatus==='PUBLISHED'?'已发布':row.lifecycleStatus==='REVOKED'?'已撤销':'草稿'}}</template></el-table-column><el-table-column label="操作" width="120"><template #default="{row}"><el-button v-if="row.lifecycleStatus==='DRAFT'" link type="success" @click="publishCredential(row.id)">发布</el-button><el-button v-if="row.lifecycleStatus==='PUBLISHED'" link type="danger" @click="revokeCredential(row.id)">撤销</el-button></template></el-table-column></el-table></div><div class="drawer-section"><div class="asset-toolbar"><div><strong>服务授权</strong><span>只有已发布授权中的业务调用编码可以使用。</span></div><el-button type="primary" @click="grantDialog=true">＋ 授权接入服务</el-button></div><el-empty v-if="!selectedApp.grants.length" description="尚未授权任何接入服务"/><el-table v-else :data="selectedApp.grants" size="small"><el-table-column prop="serviceName" label="服务名称"/><el-table-column prop="serviceCode" label="业务调用编码"/><el-table-column label="授权版本"><template #default="{row}"><el-tag v-for="version in row.versions" :key="version.id" :type="version.lifecycleStatus==='PUBLISHED'?'success':'warning'" class="grant-version-tag">v{{version.versionNo}} · {{version.lifecycleStatus==='PUBLISHED'?'已发布':'草稿'}} <el-button v-if="version.lifecycleStatus==='DRAFT'" link @click="publishGrant(row.grant.id,version.id)">发布</el-button></el-tag></template></el-table-column></el-table></div></template></el-drawer>
  <el-dialog v-model="projectDialog" title="新增调用方项目" width="560px"><el-form label-position="top"><el-form-item label="项目编码" required><el-input v-model="projectForm.projectCode" placeholder="例如 member-center"/></el-form-item><el-form-item label="项目名称" required><el-input v-model="projectForm.projectName" placeholder="例如 会员中台"/></el-form-item><el-form-item label="负责人"><el-input v-model="projectForm.ownerCode"/></el-form-item><el-form-item label="说明"><el-input v-model="projectForm.description" type="textarea"/></el-form-item><p v-if="error" class="command-validation">{{error}}</p></el-form><template #footer><el-button @click="projectDialog=false">取消</el-button><el-button type="primary" :loading="saving" @click="createProject">创建项目</el-button></template></el-dialog>
  <el-dialog v-model="appDialog" title="新增调用方应用" width="560px"><el-form label-position="top"><el-form-item label="应用编码" required><el-input v-model="appForm.appCode" placeholder="例如 member-center-prod"/></el-form-item><el-form-item label="应用名称" required><el-input v-model="appForm.appName" placeholder="例如 会员中心生产服务"/></el-form-item><el-form-item label="负责人"><el-input v-model="appForm.ownerCode"/></el-form-item><el-form-item label="说明"><el-input v-model="appForm.description" type="textarea"/></el-form-item><p v-if="error" class="command-validation">{{error}}</p></el-form><template #footer><el-button @click="appDialog=false">取消</el-button><el-button type="primary" :loading="saving" @click="createApplication">创建应用</el-button></template></el-dialog>
  <el-dialog v-model="credentialDialog" title="新建调用凭据版本" width="620px"><el-alert type="warning" :closable="false" title="平台不会保存appSecret明文。请先在Runtime进程环境中设置对应变量。"/><el-form label-position="top"><el-form-item label="Secret引用" required><el-input v-model="credentialForm.secretReference" placeholder="env://TPIP_SECRET_MEMBER_CENTER_PROD"/></el-form-item><el-form-item label="失效时间（可选）"><el-date-picker v-model="credentialForm.validUntil" type="datetime" value-format="YYYY-MM-DDTHH:mm:ss" style="width:100%"/></el-form-item><p v-if="error" class="command-validation">{{error}}</p></el-form><template #footer><el-button @click="credentialDialog=false">取消</el-button><el-button type="primary" :loading="saving" @click="createCredential">创建草稿</el-button></template></el-dialog>
  <el-dialog v-model="grantDialog" title="授权接入服务" width="680px"><el-form label-position="top"><el-form-item label="允许调用的接入服务" required><el-select v-model="grantForm.operationId" filterable style="width:100%"><el-option v-for="item in servicesQuery.data.value??[]" :key="item.id" :label="`${item.serviceName} · ${item.serviceCode}`" :value="item.id"/></el-select></el-form-item><el-form-item label="允许的业务场景（可选，逗号分隔）"><el-input v-model="grantForm.allowedScenarios" placeholder="例如 login-verification,password-reset"/></el-form-item><div class="form-two-columns"><el-form-item label="QPS限制（预留）"><el-input-number v-model="grantForm.qpsLimit" :min="1" controls-position="right"/></el-form-item><el-form-item label="授权失效时间（可选）"><el-date-picker v-model="grantForm.validUntil" type="datetime" value-format="YYYY-MM-DDTHH:mm:ss"/></el-form-item></div><el-form-item label="负责人"><el-input v-model="grantForm.ownerCode"/></el-form-item><p v-if="error" class="command-validation">{{error}}</p></el-form><template #footer><el-button @click="grantDialog=false">取消</el-button><el-button type="primary" :loading="saving" @click="createGrant">创建授权草稿</el-button></template></el-dialog>
</section></template>
<style scoped>
.consumer-layout{display:grid;grid-template-columns:260px 1fr;gap:16px;margin-top:18px}.consumer-projects{padding:14px}.consumer-section-title{display:flex;justify-content:space-between;padding:8px}.consumer-section-title button{border:0;background:none;color:var(--el-color-primary);cursor:pointer}.consumer-projects>button{display:block;width:100%;padding:12px;text-align:left;border:1px solid transparent;background:none;cursor:pointer}.consumer-projects>button.active{background:#edf8f3;border-color:#a8d8c6}.consumer-projects strong,.consumer-projects small{display:block}.consumer-projects small{margin-top:4px;color:var(--muted)}.product-table-card{padding:18px}.consumer-app-hero{padding:18px;background:#edf8f3}.consumer-app-hero span,.consumer-app-hero strong,.consumer-app-hero code{display:block}.consumer-app-hero strong{margin:6px 0;font-size:22px}.grant-version-tag{margin:2px 4px}.grant-version-tag .el-button{margin-left:5px}@media(max-width:850px){.consumer-layout{grid-template-columns:1fr}}
</style>
