<script setup lang="ts">
import { computed, reactive, ref, watch } from 'vue'
import { useMutation, useQuery, useQueryClient } from '@tanstack/vue-query'
import { ElMessage } from 'element-plus'
import { ApiError } from '@/api/http'
import AsyncStatePanel from '@/components/AsyncStatePanel.vue'
import { canonicalAssetApi } from '../api/canonicalAssetApi'
import { integrationAssetApi } from '../api/integrationAssetApi'
import { providerContractVersionApi } from '../api/providerContractVersionApi'
import { mappingAssetApi, type BindingAsset, type CreateBindingInput, type CreateMappingInput,
  type MappingAsset, type MappingDirection, type MappingFixtureResult, type MappingRuleInput,
  type MappingTargetType, type MappingVersionAsset } from '../api/mappingAssetApi'

const queryClient = useQueryClient(); const activeTab = ref('bindings'); const errorMessage = ref('')
const bindingDialog = ref(false); const mappingDialog = ref(false); const versionDialog = ref(false); const testDialog = ref(false)
const selectedMappingId = ref(0); const selectedCanonicalContractId = ref(0); const selectedCanonicalVersionId = ref(0); const selectedProviderVersionId = ref(0)
const testTarget = ref<MappingVersionAsset | null>(null); const testResult = ref<MappingFixtureResult | null>(null)

const operations = useQuery({ queryKey: ['canonical-operations'], queryFn: ({ signal }) => canonicalAssetApi.operations(undefined, signal) })
const canonicalContracts = useQuery({ queryKey: ['canonical-contracts'], queryFn: ({ signal }) => canonicalAssetApi.contracts(undefined, signal) })
const providerContracts = useQuery({ queryKey: ['integration-provider-contracts'], queryFn: ({ signal }) => integrationAssetApi.contracts(undefined, signal) })
const bindings = useQuery({ queryKey: ['integration-bindings'], queryFn: ({ signal }) => mappingAssetApi.bindings(signal) })
const mappings = useQuery({ queryKey: ['integration-mappings'], queryFn: ({ signal }) => mappingAssetApi.mappings(undefined, signal) })
const operationItems = computed(() => operations.data.value?.items ?? []); const canonicalContractItems = computed(() => canonicalContracts.data.value?.items ?? [])
const providerContractItems = computed(() => providerContracts.data.value?.items ?? []); const bindingItems = computed(() => bindings.data.value?.items ?? []); const mappingItems = computed(() => mappings.data.value?.items ?? [])
const currentMapping = computed(() => mappingItems.value.find(item => item.id === selectedMappingId.value) ?? null)
const currentBinding = computed(() => bindingItems.value.find(item => item.id === currentMapping.value?.bindingId) ?? null)
const expectedCanonicalKind = computed(() => currentMapping.value?.direction === 'OUTBOUND_REQUEST' ? 'REQUEST' : 'RESPONSE')
const availableCanonicalContracts = computed(() => canonicalContractItems.value.filter(item => item.operationId === currentBinding.value?.operationId && item.contractKind === expectedCanonicalKind.value))
const mappingVersions = useQuery({ queryKey: computed(() => ['mapping-versions', selectedMappingId.value]), queryFn: ({ signal }) => mappingAssetApi.versions(selectedMappingId.value, signal), enabled: computed(() => selectedMappingId.value > 0) })
const canonicalVersions = useQuery({ queryKey: computed(() => ['canonical-contract-versions', selectedCanonicalContractId.value]), queryFn: ({ signal }) => canonicalAssetApi.versions(selectedCanonicalContractId.value, signal), enabled: computed(() => selectedCanonicalContractId.value > 0) })
const providerVersions = useQuery({ queryKey: computed(() => ['provider-contract-versions', currentBinding.value?.providerContractId]), queryFn: ({ signal }) => providerContractVersionApi.versions(currentBinding.value!.providerContractId, signal), enabled: computed(() => Boolean(currentBinding.value?.providerContractId)) })
const publishedCanonicalVersions = computed(() => (canonicalVersions.data.value ?? []).filter(item => item.lifecycleStatus === 'PUBLISHED'))
const publishedProviderVersions = computed(() => (providerVersions.data.value ?? []).filter(item => item.lifecycleStatus === 'PUBLISHED'))

watch(mappingItems, items => { if (items.length && !items.some(item => item.id === selectedMappingId.value)) selectedMappingId.value = items[0]!.id }, { immediate: true })
watch([currentMapping, availableCanonicalContracts], () => { selectedCanonicalContractId.value = availableCanonicalContracts.value[0]?.id ?? 0; selectedCanonicalVersionId.value = 0; selectedProviderVersionId.value = 0 })
watch(publishedCanonicalVersions, items => { if (items.length && !items.some(item => item.id === selectedCanonicalVersionId.value)) selectedCanonicalVersionId.value = items[0]!.id })
watch(publishedProviderVersions, items => { if (items.length && !items.some(item => item.id === selectedProviderVersionId.value)) selectedProviderVersionId.value = items[0]!.id })

const bindingForm = reactive<CreateBindingInput>({ bindingCode: '', bindingName: '', operationId: 0, providerContractId: 0, ownerCode: '' })
const mappingForm = reactive<CreateMappingInput>({ bindingId: 0, mappingCode: '', mappingName: '', direction: 'OUTBOUND_REQUEST' })
const rules = ref<MappingRuleInput[]>([newRule(10)])
const testForm = reactive({ sourceText: '{}', requestId: 'local-mapping-test', traceId: 'local-mapping-test' })
function newRule(order: number): MappingRuleInput { return { ruleCode: `field-${order}`, ruleOrder: order, valueSource: 'SELECTOR', sourceSelector: '$.', targetSelector: '$.', targetType: 'STRING', constantValue: null, defaultValue: null, converterCode: null, converterConfig: null, conditionExpression: null, required: true, arrayStrategy: null, missingStrategy: 'FAIL', errorStrategy: 'FAIL', enabled: true } }
function message(error: Error): string { return error instanceof ApiError ? error.message : '请求失败，请确认 Control Plane 状态。' }
function requireCode(code: string): boolean { return /^[a-z][a-z0-9]*(?:[._-][a-z0-9]+)*$/.test(code) }
function invalidate(): void { void queryClient.invalidateQueries({ queryKey: ['integration-bindings'] }); void queryClient.invalidateQueries({ queryKey: ['integration-mappings'] }) }
const createBinding = useMutation({ mutationFn: (input: CreateBindingInput) => mappingAssetApi.createBinding(input), onSuccess: () => { bindingDialog.value = false; invalidate(); ElMessage.success('Binding 已创建') }, onError: (e: Error) => { errorMessage.value = message(e) } })
const createMapping = useMutation({ mutationFn: (input: CreateMappingInput) => mappingAssetApi.createMapping(input), onSuccess: result => { mappingDialog.value = false; selectedMappingId.value = result.id; invalidate(); ElMessage.success('Mapping 已创建') }, onError: (e: Error) => { errorMessage.value = message(e) } })
const createVersion = useMutation({ mutationFn: (input: Parameters<typeof mappingAssetApi.createVersion>[1]) => mappingAssetApi.createVersion(selectedMappingId.value, input), onSuccess: () => { versionDialog.value = false; void mappingVersions.refetch(); ElMessage.success('MappingVersion 已创建') }, onError: (e: Error) => { errorMessage.value = message(e) } })
const publish = useMutation({ mutationFn: (row: MappingVersionAsset) => mappingAssetApi.publishVersion(row.mappingId, row.id), onSuccess: () => { void mappingVersions.refetch(); ElMessage.success('MappingVersion 已发布') }, onError: (e: Error) => { errorMessage.value = message(e) } })
const testVersion = useMutation({ mutationFn: (input: { row: MappingVersionAsset; source: unknown; operationCode: string }) => mappingAssetApi.testVersion(input.row.mappingId, input.row.id, { source: input.source, requestId: testForm.requestId, traceId: testForm.traceId, operationCode: input.operationCode, attributes: {} }), onSuccess: result => { testResult.value = result }, onError: (e: Error) => { errorMessage.value = message(e) } })
function submitBinding(): void { errorMessage.value = ''; if (!bindingForm.operationId || !bindingForm.providerContractId || !requireCode(bindingForm.bindingCode) || !bindingForm.bindingName.trim() || !bindingForm.ownerCode.trim()) { errorMessage.value = '请选择 Operation 和 ProviderContract，并填写合法编码、名称和负责人。'; return }; createBinding.mutate({ ...bindingForm }) }
function submitMapping(): void { errorMessage.value = ''; if (!mappingForm.bindingId || !requireCode(mappingForm.mappingCode) || !mappingForm.mappingName.trim()) { errorMessage.value = '请选择 Binding，并填写合法 Mapping 编码和名称。'; return }; createMapping.mutate({ ...mappingForm }) }
function schemaRefs(): { sourceSchemaRef: string; targetSchemaRef: string } | null {
  const binding = currentBinding.value; const mapping = currentMapping.value
  if (!binding || !mapping || !selectedCanonicalContractId.value || !selectedCanonicalVersionId.value || !selectedProviderVersionId.value) return null
  const canonical = `canonical-contract-version:${selectedCanonicalContractId.value}:${selectedCanonicalVersionId.value}`
  const provider = `provider-contract-version:${binding.providerContractId}:${selectedProviderVersionId.value}`
  return mapping.direction === 'OUTBOUND_REQUEST' ? { sourceSchemaRef: canonical, targetSchemaRef: provider } : { sourceSchemaRef: provider, targetSchemaRef: canonical }
}
function submitVersion(): void {
  errorMessage.value = ''; const refs = schemaRefs()
  if (!refs) { errorMessage.value = '必须选择已发布的业务标准报文版本和第三方报文结构版本。'; return }
  if (!rules.value.length || rules.value.some(rule => !requireCode(rule.ruleCode) || !rule.sourceSelector?.startsWith('$') || !rule.targetSelector.startsWith('$'))) { errorMessage.value = '至少需要一条规则，编码必须合法，Source/Target Selector 必须以 $ 开头。'; return }
  createVersion.mutate({ selectorProfile: 'JSONPATH_1_0', ...refs, mappingOptions: {}, rules: rules.value.map(rule => ({ ...rule })) })
}
function addRule(): void { rules.value.push(newRule((rules.value.length + 1) * 10)) }
function removeRule(index: number): void { if (rules.value.length > 1) rules.value.splice(index, 1) }
function bindingName(id: number): string { const item = bindingItems.value.find(value => value.id === id); return item ? `${item.bindingName} · ${item.bindingCode}` : `Binding #${id}` }
function operationName(id: number): string { const item = operationItems.value.find(value => value.id === id); return item ? `${item.operationName} · ${item.operationCode}` : `Operation #${id}` }
function providerContractName(id: number): string { const item = providerContractItems.value.find(value => value.id === id); return item ? `${item.contractName} · ${item.contractCode}` : `第三方接口 #${id}` }
function requestPublish(row: unknown): void { publish.mutate(row as MappingVersionAsset) }
function openTest(row: unknown): void { testTarget.value = row as MappingVersionAsset; testResult.value = null; testDialog.value = true }
function runTest(): void { errorMessage.value = ''; if (!testTarget.value || !currentBinding.value) return; try { const source = JSON.parse(testForm.sourceText) as unknown; const operationCode = operationItems.value.find(item => item.id === currentBinding.value?.operationId)?.operationCode ?? ''; testVersion.mutate({ row: testTarget.value, source, operationCode }) } catch { errorMessage.value = '测试输入不是合法 JSON。' } }
</script>

<template>
  <section>
    <div class="page-heading"><div><h2>JSONPath 字段映射</h2><p>通过 Binding 连接标准 Operation 与第三方 Contract，配置请求和响应的双向字段转换。</p></div><el-tag effect="plain">JSONPATH 1.0</el-tag></div>
    <el-alert v-if="errorMessage" class="command-notice" type="error" :title="errorMessage" closable @close="errorMessage = ''" show-icon />
    <el-alert class="command-notice" type="info" :closable="false" title="Schema 引用由选择结果自动生成；Mapping 只允许引用已发布且属于当前 Binding 的 Contract Version。" show-icon />
    <div class="surface integration-asset-tabs mapping-tabs"><el-tabs v-model="activeTab">
      <el-tab-pane label="Binding" name="bindings"><div class="asset-toolbar"><div><strong>适配关系</strong><span>连接一个业务标准接口和一个第三方接口。</span></div><el-button type="primary" :disabled="!operationItems.length || !providerContractItems.length" @click="bindingDialog = true">新增 Binding</el-button></div><AsyncStatePanel :loading="bindings.isPending.value" :error="bindings.isError.value" error-title="Binding 读取失败" @retry="bindings.refetch()"><el-empty v-if="!bindingItems.length" description="尚未创建 Binding" /><el-table v-else :data="bindingItems"><el-table-column label="Binding" min-width="260"><template #default="{ row }"><strong>{{ row.bindingName }}</strong><div class="subtle mono">{{ row.bindingCode }}</div></template></el-table-column><el-table-column label="业务标准接口" min-width="240"><template #default="{ row }">{{ operationName(row.operationId) }}</template></el-table-column><el-table-column label="第三方接口" min-width="260"><template #default="{ row }">{{ providerContractName(row.providerContractId) }}</template></el-table-column><el-table-column prop="status" label="状态" width="100" /></el-table></AsyncStatePanel></el-tab-pane>
      <el-tab-pane label="Mapping" name="mappings"><div class="asset-toolbar"><div><strong>Mapping 稳定身份</strong><span>核心方向为 OUTBOUND_REQUEST 和 INBOUND_RESPONSE。</span></div><el-button type="primary" :disabled="!bindingItems.length" @click="mappingDialog = true">新增 Mapping</el-button></div><AsyncStatePanel :loading="mappings.isPending.value" :error="mappings.isError.value" error-title="Mapping 读取失败" @retry="mappings.refetch()"><el-empty v-if="!mappingItems.length" description="尚未创建 Mapping" /><el-table v-else :data="mappingItems"><el-table-column label="Mapping" min-width="280"><template #default="{ row }"><strong>{{ row.mappingName }}</strong><div class="subtle mono">{{ row.mappingCode }}</div></template></el-table-column><el-table-column label="Binding" min-width="240"><template #default="{ row }">{{ bindingName(row.bindingId) }}</template></el-table-column><el-table-column prop="direction" label="方向" width="190" /><el-table-column prop="status" label="状态" width="100" /><el-table-column label="版本" width="100"><template #default="{ row }"><el-button link type="primary" @click="selectedMappingId = row.id; activeTab = 'versions'">管理</el-button></template></el-table-column></el-table></AsyncStatePanel></el-tab-pane>
      <el-tab-pane label="MappingVersion" name="versions"><div class="asset-toolbar canonical-version-toolbar"><div><strong>映射规则版本</strong><span>不可变规则集，可在发布前反复执行样例测试。</span></div><div><el-select v-model="selectedMappingId" filterable placeholder="选择 Mapping"><el-option v-for="item in mappingItems" :key="item.id" :label="`${item.mappingName} · ${item.direction}`" :value="item.id" /></el-select><el-button type="primary" :disabled="!selectedMappingId" @click="versionDialog = true">新增 Version</el-button></div></div><AsyncStatePanel :loading="mappingVersions.isPending.value" :error="mappingVersions.isError.value" error-title="MappingVersion 读取失败" @retry="mappingVersions.refetch()"><el-empty v-if="!mappingVersions.data.value?.length" description="该 Mapping 尚未创建版本" /><el-table v-else :data="mappingVersions.data.value"><el-table-column label="Revision" width="110"><template #default="{ row }"><strong>{{ row.versionNo }}</strong></template></el-table-column><el-table-column label="Schema Reference" min-width="390"><template #default="{ row }"><div class="schema-ref mono">{{ row.sourceSchemaRef }}</div><div class="schema-ref mono">→ {{ row.targetSchemaRef }}</div></template></el-table-column><el-table-column label="规则" width="80"><template #default="{ row }">{{ row.rules.length }}</template></el-table-column><el-table-column label="Checksum" min-width="250"><template #default="{ row }"><span class="mono checksum-cell">{{ row.contentChecksum }}</span></template></el-table-column><el-table-column label="状态" width="110"><template #default="{ row }"><el-tag :type="row.lifecycleStatus === 'PUBLISHED' ? 'success' : 'warning'">{{ row.lifecycleStatus }}</el-tag></template></el-table-column><el-table-column label="操作" width="140"><template #default="{ row }"><el-button link type="primary" @click="openTest(row)">测试</el-button><el-button v-if="row.lifecycleStatus === 'DRAFT'" link type="primary" :loading="publish.isPending.value" @click="requestPublish(row)">发布</el-button></template></el-table-column></el-table></AsyncStatePanel></el-tab-pane>
    </el-tabs></div>

    <el-dialog v-model="bindingDialog" title="新增 Binding" width="650px"><el-form label-position="top"><el-form-item label="业务标准接口" required><el-select v-model="bindingForm.operationId" filterable style="width:100%"><el-option v-for="item in operationItems" :key="item.id" :label="operationName(item.id)" :value="item.id" /></el-select></el-form-item><el-form-item label="第三方接口" required><el-select v-model="bindingForm.providerContractId" filterable style="width:100%"><el-option v-for="item in providerContractItems" :key="item.id" :label="providerContractName(item.id)" :value="item.id" /></el-select></el-form-item><div class="form-two-columns"><el-form-item label="Binding 编码" required><el-input v-model="bindingForm.bindingCode" placeholder="customer.lookup.vendor" /></el-form-item><el-form-item label="名称" required><el-input v-model="bindingForm.bindingName" /></el-form-item></div><el-form-item label="负责人" required><el-input v-model="bindingForm.ownerCode" /></el-form-item></el-form><template #footer><el-button @click="bindingDialog = false">取消</el-button><el-button type="primary" :loading="createBinding.isPending.value" @click="submitBinding">创建</el-button></template></el-dialog>
    <el-dialog v-model="mappingDialog" title="新增 Mapping" width="620px"><el-form label-position="top"><el-form-item label="Binding" required><el-select v-model="mappingForm.bindingId" filterable style="width:100%"><el-option v-for="item in bindingItems" :key="item.id" :label="bindingName(item.id)" :value="item.id" /></el-select></el-form-item><div class="form-two-columns"><el-form-item label="Mapping 编码" required><el-input v-model="mappingForm.mappingCode" placeholder="customer.lookup.outbound" /></el-form-item><el-form-item label="名称" required><el-input v-model="mappingForm.mappingName" /></el-form-item></div><el-form-item label="方向" required><el-select v-model="mappingForm.direction" style="width:100%"><el-option v-for="item in (['OUTBOUND_REQUEST','INBOUND_RESPONSE'] as MappingDirection[])" :key="item" :value="item" /></el-select></el-form-item></el-form><template #footer><el-button @click="mappingDialog = false">取消</el-button><el-button type="primary" :loading="createMapping.isPending.value" @click="submitMapping">创建</el-button></template></el-dialog>
    <el-dialog v-model="versionDialog" title="新增 MappingVersion" width="1050px"><el-alert type="info" :closable="false" :title="`方向：${currentMapping?.direction ?? '—'}；Schema 引用会按方向自动生成。`" show-icon /><el-form class="dialog-form" label-position="top"><div class="form-two-columns"><el-form-item :label="`Canonical ${expectedCanonicalKind}`" required><el-select v-model="selectedCanonicalContractId" filterable><el-option v-for="item in availableCanonicalContracts" :key="item.id" :label="`${item.contractName} · ${item.contractCode}`" :value="item.id" /></el-select></el-form-item><el-form-item label="Canonical Published Version" required><el-select v-model="selectedCanonicalVersionId"><el-option v-for="item in publishedCanonicalVersions" :key="item.id" :label="`${item.semanticVersion} · Revision ${item.versionNo}`" :value="item.id" /></el-select></el-form-item><el-form-item label="ProviderContract"><el-input :model-value="currentBinding ? providerContractName(currentBinding.providerContractId) : ''" disabled /></el-form-item><el-form-item label="Provider Published Version" required><el-select v-model="selectedProviderVersionId"><el-option v-for="item in publishedProviderVersions" :key="item.id" :label="`${item.semanticVersion} · Revision ${item.versionNo}`" :value="item.id" /></el-select></el-form-item></div><div class="rule-editor-heading"><strong>JSONPath Rules</strong><el-button @click="addRule">增加规则</el-button></div><div v-for="(rule,index) in rules" :key="index" class="mapping-rule-card"><div class="mapping-rule-grid"><el-form-item label="Rule Code" required><el-input v-model="rule.ruleCode" /></el-form-item><el-form-item label="Order"><el-input-number v-model="rule.ruleOrder" :min="0" /></el-form-item><el-form-item label="Source JSONPath" required><el-input v-model="rule.sourceSelector" class="mono" /></el-form-item><el-form-item label="Target JSONPath" required><el-input v-model="rule.targetSelector" class="mono" /></el-form-item><el-form-item label="Target Type"><el-select v-model="rule.targetType"><el-option v-for="item in (['STRING','NUMBER','BOOLEAN','OBJECT','ARRAY'] as MappingTargetType[])" :key="item" :value="item" /></el-select></el-form-item><el-form-item label="缺失策略"><el-select v-model="rule.missingStrategy"><el-option value="FAIL" /><el-option value="IGNORE" /><el-option value="DEFAULT" /></el-select></el-form-item><el-form-item label="错误策略"><el-select v-model="rule.errorStrategy"><el-option value="FAIL" /><el-option value="IGNORE" /><el-option value="USE_DEFAULT" /></el-select></el-form-item><el-form-item label="必填"><el-switch v-model="rule.required" /></el-form-item></div><el-button link type="danger" :disabled="rules.length === 1" @click="removeRule(index)">删除规则</el-button></div></el-form><template #footer><el-button @click="versionDialog = false">取消</el-button><el-button type="primary" :loading="createVersion.isPending.value" @click="submitVersion">创建 DRAFT</el-button></template></el-dialog>
    <el-dialog v-model="testDialog" title="Mapping 样例测试" width="760px"><el-form label-position="top"><el-form-item label="Source JSON" required><el-input v-model="testForm.sourceText" type="textarea" :rows="10" class="schema-editor" /></el-form-item><div class="form-two-columns"><el-form-item label="Request ID"><el-input v-model="testForm.requestId" /></el-form-item><el-form-item label="Trace ID"><el-input v-model="testForm.traceId" /></el-form-item></div></el-form><div v-if="testResult" class="mapping-test-result" :class="{ 'mapping-test-result--failed': !testResult.successful }"><strong>{{ testResult.successful ? '测试通过' : '测试失败' }}</strong><small class="mono">Plan {{ testResult.compiledPlanChecksum }}</small><pre>{{ JSON.stringify(testResult.output, null, 2) }}</pre><pre v-if="testResult.diagnostics.length">{{ JSON.stringify(testResult.diagnostics, null, 2) }}</pre></div><template #footer><el-button @click="testDialog = false">关闭</el-button><el-button type="primary" :loading="testVersion.isPending.value" @click="runTest">执行测试</el-button></template></el-dialog>
  </section>
</template>
