<script setup lang="ts">
import { computed, reactive, ref, watch } from 'vue'
import { useMutation, useQuery, useQueryClient } from '@tanstack/vue-query'
import { ElMessage } from 'element-plus'
import { ApiError } from '@/api/http'
import AsyncStatePanel from '@/components/AsyncStatePanel.vue'
import { mappingAssetApi } from '../api/mappingAssetApi'
import { policyAssetApi, type CreatePolicyInput, type PolicyVersionAsset } from '../api/policyAssetApi'

const queryClient = useQueryClient(); const activeTab = ref('registry'); const errorMessage = ref('')
const policyDialog = ref(false); const versionDialog = ref(false); const planDialog = ref(false); const selectedPolicyId = ref(0)
const selectedPlan = ref<Record<string, unknown> | null>(null)
const types = useQuery({ queryKey: ['policy-types'], queryFn: ({ signal }) => policyAssetApi.types(signal) })
const bindings = useQuery({ queryKey: ['integration-bindings'], queryFn: ({ signal }) => mappingAssetApi.bindings(signal) })
const policies = useQuery({ queryKey: ['integration-policies'], queryFn: ({ signal }) => policyAssetApi.policies(undefined, signal) })
const bindingItems = computed(() => bindings.data.value?.items ?? []); const policyItems = computed(() => policies.data.value?.items ?? [])
const versions = useQuery({ queryKey: computed(() => ['policy-versions', selectedPolicyId.value]), queryFn: ({ signal }) => policyAssetApi.versions(selectedPolicyId.value, signal), enabled: computed(() => selectedPolicyId.value > 0) })
watch(policyItems, items => { if (items.length && !items.some(item => item.id === selectedPolicyId.value)) selectedPolicyId.value = items[0]!.id }, { immediate: true })
const policyForm = reactive<CreatePolicyInput>({ bindingId: 0, policyCode: '', policyName: '' })
const documentText = ref(JSON.stringify({ apiVersion: 'tpip.policy/v1alpha1', kind: 'PolicyChain', stages: { AFTER_REQUEST_MAPPING: [{ id: 'inject-request-id', use: 'builtin.transport.inject@1.0.0', with: { headers: { 'X-Request-Id': '${context.requestId}' } }, onFailure: 'FAIL' }], BEFORE_TRANSPORT: [{ id: 'provider-api-key', use: 'builtin.auth.api-key@1.0.0', with: { secretRef: 'env://TPIP_SECRET_', headerName: 'X-API-Key', prefix: '' }, onFailure: 'FAIL' }] } }, null, 2))
function message(error: Error): string { return error instanceof ApiError ? error.message : '请求失败，请确认 Control Plane 状态。' }
function requireCode(code: string): boolean { return /^[a-z][a-z0-9]*(?:[._-][a-z0-9]+)*$/.test(code) }
const createPolicy = useMutation({ mutationFn: (input: CreatePolicyInput) => policyAssetApi.createPolicy(input), onSuccess: result => { policyDialog.value = false; selectedPolicyId.value = result.id; void queryClient.invalidateQueries({ queryKey: ['integration-policies'] }); ElMessage.success('Policy 已创建') }, onError: (e: Error) => { errorMessage.value = message(e) } })
const createVersion = useMutation({ mutationFn: (document: unknown) => policyAssetApi.createVersion(selectedPolicyId.value, document), onSuccess: () => { versionDialog.value = false; void versions.refetch(); ElMessage.success('Policy DSL 编译通过并已创建 DRAFT') }, onError: (e: Error) => { errorMessage.value = `Policy 编译失败：${message(e)}` } })
const publish = useMutation({ mutationFn: (row: PolicyVersionAsset) => policyAssetApi.publishVersion(row.policyId, row.id), onSuccess: () => { void versions.refetch(); ElMessage.success('PolicyVersion 已发布') }, onError: (e: Error) => { errorMessage.value = message(e) } })
const loadPlan = useMutation({ mutationFn: (row: PolicyVersionAsset) => policyAssetApi.plan(row.policyId, row.id), onSuccess: plan => { selectedPlan.value = plan; planDialog.value = true }, onError: (e: Error) => { errorMessage.value = message(e) } })
function submitPolicy(): void { errorMessage.value = ''; if (!policyForm.bindingId || !requireCode(policyForm.policyCode) || !policyForm.policyName.trim()) { errorMessage.value = '请选择 Binding，并填写合法 Policy 编码和名称。'; return }; createPolicy.mutate({ ...policyForm }) }
function submitVersion(): void { errorMessage.value = ''; try { createVersion.mutate(JSON.parse(documentText.value) as unknown) } catch { errorMessage.value = 'Policy DSL 不是合法 JSON。' } }
function bindingName(id: number): string { const item = bindingItems.value.find(value => value.id === id); return item ? `${item.bindingName} · ${item.bindingCode}` : `Binding #${id}` }
function requestPublish(row: unknown): void { publish.mutate(row as PolicyVersionAsset) }
function requestPlan(row: unknown): void { loadPlan.mutate(row as PolicyVersionAsset) }
</script>

<template>
  <section>
    <div class="page-heading"><div><h2>Policy DSL</h2><p>用注册、类型化的 Policy 能力配置认证和受控 Header 注入，不执行任意 Groovy。</p></div><el-tag effect="plain">tpip.policy/v1alpha1</el-tag></div>
    <el-alert v-if="errorMessage" class="command-notice" type="error" :title="errorMessage" closable @close="errorMessage = ''" show-icon />
    <el-alert class="command-notice" type="warning" :closable="false" title="Secret 只能使用 env://TPIP_SECRET_* 引用。DSL 创建时立即编译，失败不会生成版本。" show-icon />
    <div class="surface integration-asset-tabs policy-config-tabs"><el-tabs v-model="activeTab">
      <el-tab-pane label="Policy Type Registry" name="registry"><div class="asset-toolbar"><div><strong>受控能力注册表</strong><span>只有 ACTIVE 类型及其允许的挂载阶段可以进入 Policy DSL。</span></div></div><AsyncStatePanel :loading="types.isPending.value" :error="types.isError.value" error-title="Policy Type 读取失败" @retry="types.refetch()"><el-table :data="types.data.value ?? []"><el-table-column label="Policy Type" min-width="250"><template #default="{ row }"><strong>{{ row.policyTypeCode }}@{{ row.semanticVersion }}</strong><div class="subtle">{{ row.implementationKind }} · {{ row.runtimeCompatibility }}</div></template></el-table-column><el-table-column label="允许阶段" min-width="250"><template #default="{ row }"><el-tag v-for="stage in row.allowedStages" :key="stage" size="small">{{ stage }}</el-tag></template></el-table-column><el-table-column prop="securityClassification" label="安全级别" width="120" /><el-table-column label="属性" width="180"><template #default="{ row }"><span>{{ row.deterministic ? '确定性' : '非确定性' }} · {{ row.sideEffect ? '有副作用' : '无副作用' }}</span></template></el-table-column><el-table-column prop="status" label="状态" width="100" /></el-table></AsyncStatePanel></el-tab-pane>
      <el-tab-pane label="Policy" name="policies"><div class="asset-toolbar"><div><strong>Policy 稳定身份</strong><span>Policy 从属于 Binding，版本负责冻结 DSL 内容。</span></div><el-button type="primary" :disabled="!bindingItems.length" @click="policyDialog = true">新增 Policy</el-button></div><AsyncStatePanel :loading="policies.isPending.value" :error="policies.isError.value" error-title="Policy 读取失败" @retry="policies.refetch()"><el-empty v-if="!policyItems.length" description="尚未创建 Policy" /><el-table v-else :data="policyItems"><el-table-column label="Policy" min-width="280"><template #default="{ row }"><strong>{{ row.policyName }}</strong><div class="subtle mono">{{ row.policyCode }}</div></template></el-table-column><el-table-column label="Binding" min-width="280"><template #default="{ row }">{{ bindingName(row.bindingId) }}</template></el-table-column><el-table-column prop="status" label="状态" width="100" /><el-table-column label="版本" width="100"><template #default="{ row }"><el-button link type="primary" @click="selectedPolicyId = row.id; activeTab = 'versions'">管理</el-button></template></el-table-column></el-table></AsyncStatePanel></el-tab-pane>
      <el-tab-pane label="PolicyVersion" name="versions"><div class="asset-toolbar canonical-version-toolbar"><div><strong>编译后的不可变版本</strong><span>创建时编译，发布时再次编译并校验注册表。</span></div><div><el-select v-model="selectedPolicyId" filterable placeholder="选择 Policy"><el-option v-for="item in policyItems" :key="item.id" :label="`${item.policyName} · ${item.policyCode}`" :value="item.id" /></el-select><el-button type="primary" :disabled="!selectedPolicyId" @click="versionDialog = true">新增 DSL Version</el-button></div></div><AsyncStatePanel :loading="versions.isPending.value" :error="versions.isError.value" error-title="PolicyVersion 读取失败" @retry="versions.refetch()"><el-empty v-if="!versions.data.value?.length" description="该 Policy 尚未创建版本" /><el-table v-else :data="versions.data.value"><el-table-column label="Revision" width="100"><template #default="{ row }"><strong>{{ row.versionNo }}</strong></template></el-table-column><el-table-column prop="dslApiVersion" label="DSL API" width="190" /><el-table-column prop="compilerVersion" label="Compiler" width="210" /><el-table-column label="编译" width="110"><template #default="{ row }"><el-tag :type="row.compileStatus === 'COMPILED' ? 'success' : 'danger'">{{ row.compileStatus }}</el-tag></template></el-table-column><el-table-column label="Checksum" min-width="290"><template #default="{ row }"><span class="mono checksum-cell">{{ row.contentChecksum }}</span></template></el-table-column><el-table-column label="状态" width="110"><template #default="{ row }"><el-tag :type="row.lifecycleStatus === 'PUBLISHED' ? 'success' : 'warning'">{{ row.lifecycleStatus }}</el-tag></template></el-table-column><el-table-column label="操作" width="150"><template #default="{ row }"><el-button link type="primary" @click="requestPlan(row)">计划</el-button><el-button v-if="row.lifecycleStatus === 'DRAFT'" link type="primary" @click="requestPublish(row)">发布</el-button></template></el-table-column></el-table></AsyncStatePanel></el-tab-pane>
    </el-tabs></div>
    <el-dialog v-model="policyDialog" title="新增 Policy" width="620px"><el-form label-position="top"><el-form-item label="Binding" required><el-select v-model="policyForm.bindingId" filterable style="width:100%"><el-option v-for="item in bindingItems" :key="item.id" :label="bindingName(item.id)" :value="item.id" /></el-select></el-form-item><div class="form-two-columns"><el-form-item label="Policy 编码" required><el-input v-model="policyForm.policyCode" placeholder="customer.lookup.runtime-policy" /></el-form-item><el-form-item label="名称" required><el-input v-model="policyForm.policyName" /></el-form-item></div></el-form><template #footer><el-button @click="policyDialog = false">取消</el-button><el-button type="primary" :loading="createPolicy.isPending.value" @click="submitPolicy">创建</el-button></template></el-dialog>
    <el-dialog v-model="versionDialog" title="新增 Policy DSL Version" width="900px"><el-alert type="info" :closable="false" title="模板演示 Request ID 与 API Key 注入。删除不需要的 Stage，并补充真实的 Secret 引用。" show-icon /><el-input v-model="documentText" type="textarea" :rows="25" class="schema-editor policy-editor" /><template #footer><el-button @click="versionDialog = false">取消</el-button><el-button type="primary" :loading="createVersion.isPending.value" @click="submitVersion">编译并创建 DRAFT</el-button></template></el-dialog>
    <el-dialog v-model="planDialog" title="Compiled Policy Plan" width="820px"><pre class="plan-preview">{{ JSON.stringify(selectedPlan, null, 2) }}</pre><template #footer><el-button @click="planDialog = false">关闭</el-button></template></el-dialog>
  </section>
</template>
