package com.ftk.tpip.control.application.release;
import static org.junit.jupiter.api.Assertions.*;import com.ftk.tpip.control.configuration.GlobalImpactSchedulingProperties;import com.ftk.tpip.release.domain.model.*;import com.ftk.tpip.release.domain.repository.GlobalDriftPolicyImpactJobRepository;import io.micrometer.core.instrument.simple.SimpleMeterRegistry;import java.lang.reflect.Proxy;import java.time.*;import java.util.*;import org.junit.jupiter.api.Test;
class GlobalImpactJobSchedulingServiceTest{
 @Test void claimPassesClusterBudgetAndDynamicBatchBounds(){var captured=new ArrayList<Object[]>();var repo=proxy((n,a)->{if(n.equals("claimRunnableDispatches")){captured.add(a);return List.of();}if(n.equals("countActiveDispatches"))return 0;return null;});var p=new GlobalImpactSchedulingProperties();p.setMaximumActiveDispatches(7);p.setMinimumBatchSize(3);p.setMaximumBatchSize(40);
  service(repo,p).claim("worker-1",5);assertEquals(7,captured.get(0)[4]);assertEquals(3,captured.get(0)[5]);assertEquals(40,captured.get(0)[6]);}
 @Test void workerWithoutDispatchLeaseCannotRun(){var repo=proxy((n,a)->n.equals("findRuntimeState")?Optional.of(state("worker-a",Instant.now().plusSeconds(30))):null);var scheduling=service(repo,new GlobalImpactSchedulingProperties());assertThrows(IllegalArgumentException.class,()->scheduling.runReserved(job().jobId(),5,"worker-b",null));}
 @Test void expiredDispatchLeaseAllowsRecoveryRecommendation(){var repo=proxy((n,a)->n.equals("findRuntimeState")?Optional.of(state("dead-worker",Instant.now().minusSeconds(1))):null);assertEquals("REDISPATCH_AFTER_LEASE_EXPIRY",service(repo,new GlobalImpactSchedulingProperties()).state(job().jobId()).recoveryRecommendation());}
 private static GlobalImpactJobSchedulingService service(GlobalDriftPolicyImpactJobRepository repo,GlobalImpactSchedulingProperties p){return new GlobalImpactJobSchedulingService(repo,p,new GlobalImpactJobSchedulingMetrics(new SimpleMeterRegistry()));}
 private static GlobalImpactJobRuntimeState state(String owner,Instant until){return new GlobalImpactJobRuntimeState(job(),GlobalImpactJobPriority.NORMAL,1,Instant.now().minusSeconds(100),Instant.now().minusSeconds(100),owner,until,100,"REDISPATCH_AFTER_LEASE_EXPIRY");}
 private static GlobalDriftPolicyImpactJob job(){var now=Instant.now();return new GlobalDriftPolicyImpactJob("00000000-0000-0000-0000-000000000001",1,1,"a".repeat(64),"b".repeat(64),1,0,0,GlobalDriftPolicyImpactJobStatus.RUNNING,now.minusSeconds(200),now.plusSeconds(600),null,1,"a",now.minusSeconds(200),"a",now);}
 @SuppressWarnings("unchecked")private static GlobalDriftPolicyImpactJobRepository proxy(Handler h){return (GlobalDriftPolicyImpactJobRepository)Proxy.newProxyInstance(GlobalDriftPolicyImpactJobRepository.class.getClassLoader(),new Class<?>[]{GlobalDriftPolicyImpactJobRepository.class},(p,m,a)->h.call(m.getName(),a==null?new Object[0]:a));}interface Handler{Object call(String n,Object[] a);}}
