package com.ftk.tpip.control.api.integration;

import com.fasterxml.jackson.core.JsonProcessingException;import com.fasterxml.jackson.databind.*;import com.ftk.tpip.control.application.integration.*;import com.ftk.tpip.integration.domain.model.*;import com.ftk.tpip.policy.ir.CompiledPolicyPlan;import jakarta.validation.Valid;import jakarta.validation.constraints.*;import java.net.URI;import java.time.Instant;import java.util.List;import org.springframework.http.ResponseEntity;import org.springframework.validation.annotation.Validated;import org.springframework.web.bind.annotation.*;
@Validated @RestController @RequestMapping("/control/v1/policies") public class IntegrationPolicyController{private final IntegrationPolicyApplicationService service;private final ObjectMapper json;public IntegrationPolicyController(IntegrationPolicyApplicationService s,ObjectMapper j){service=s;json=j;}
@PostMapping public ResponseEntity<Response>create(@Valid@RequestBody Create r,@RequestHeader("X-Operator")@NotBlank@Size(max=100)String actor){var p=service.create(r.bindingId,r.policyCode,r.policyName,actor);return ResponseEntity.created(URI.create("/control/v1/policies/"+p.id())).body(Response.from(p));}@GetMapping("/{id}")public Response get(@PathVariable@Min(1)long id){return Response.from(service.get(id));}@GetMapping public Page list(@RequestParam(required=false)@Min(1)Long bindingId,@RequestParam(required=false)String keyword,@RequestParam(required=false)PolicyStatus status,@RequestParam(defaultValue="0")@Min(0)int page,@RequestParam(defaultValue="20")@Min(1)@Max(200)int size){var p=service.list(bindingId,keyword,status,page,size);return new Page(p.items().stream().map(Response::from).toList(),page,size,p.totalElements());}@PutMapping("/{id}")public Response update(@PathVariable@Min(1)long id,@Valid@RequestBody Update r,@RequestHeader("X-Operator")@NotBlank@Size(max=100)String actor){return Response.from(service.update(id,r.policyName,r.status,r.rowVersion,actor));}
@PostMapping("/{id}/versions")public ResponseEntity<VersionResponse>versionCreate(@PathVariable@Min(1)long id,@Valid@RequestBody CreateVersion r,@RequestHeader("X-Operator")@NotBlank@Size(max=100)String actor){var v=service.createVersion(id,r.document,actor);return ResponseEntity.created(URI.create("/control/v1/policies/"+id+"/versions/"+v.id())).body(version(v));}@GetMapping("/{id}/versions")public List<VersionResponse>versions(@PathVariable@Min(1)long id){return service.versions(id).stream().map(this::version).toList();}@GetMapping("/{id}/versions/{versionId}")public VersionResponse version(@PathVariable@Min(1)long id,@PathVariable@Min(1)long versionId){return version(service.version(id,versionId));}@GetMapping("/{id}/versions/{versionId}/plan")public CompiledPolicyPlan plan(@PathVariable@Min(1)long id,@PathVariable@Min(1)long versionId){return service.plan(id,versionId);}@PostMapping("/{id}/versions/{versionId}:publish")public VersionResponse publish(@PathVariable@Min(1)long id,@PathVariable@Min(1)long versionId,@RequestHeader("X-Operator")@NotBlank@Size(max=100)String actor){return version(service.publish(id,versionId,actor));}
private VersionResponse version(IntegrationPolicyVersion v){return new VersionResponse(v.id(),v.policyId(),v.versionNo(),v.dslApiVersion(),read(v.normalizedDocument()),v.compilerVersion(),v.compileStatus(),read(v.compileDiagnostics()),v.contentChecksum(),v.lifecycleStatus(),v.publishedAt(),v.createdAt());}private JsonNode read(String v){if(v==null)return null;try{return json.readTree(v);}catch(JsonProcessingException e){throw new IllegalStateException(e);}}
public record Create(@Positive long bindingId,@NotBlank@Size(max=200)@Pattern(regexp="^[a-z][a-z0-9]*(?:[._-][a-z0-9]+)*$")String policyCode,@NotBlank@Size(max=200)String policyName){}public record Update(@NotBlank@Size(max=200)String policyName,@NotNull PolicyStatus status,@PositiveOrZero long rowVersion){}public record CreateVersion(@NotNull JsonNode document){}public record Response(long id,long bindingId,String policyCode,String policyName,PolicyStatus status,long rowVersion,Instant createdAt,Instant updatedAt){static Response from(IntegrationPolicy p){return new Response(p.id(),p.bindingId(),p.policyCode().value(),p.policyName(),p.status(),p.rowVersion(),p.createdAt(),p.updatedAt());}}public record Page(List<Response>items,int page,int size,long totalElements){}public record VersionResponse(long id,long policyId,int versionNo,String dslApiVersion,JsonNode normalizedDocument,String compilerVersion,PolicyCompileStatus compileStatus,JsonNode compileDiagnostics,String contentChecksum,PolicyLifecycleStatus lifecycleStatus,Instant publishedAt,Instant createdAt){}
}
