package com.ftk.tpip.control.api.release;

import com.fasterxml.jackson.core.JsonProcessingException;import com.fasterxml.jackson.databind.*;
import com.ftk.tpip.control.application.release.ReleaseApplicationService;
import com.ftk.tpip.release.domain.model.*;
import jakarta.validation.Valid;import jakarta.validation.constraints.*;
import java.net.URI;import java.time.Instant;import java.util.*;
import org.springframework.http.ResponseEntity;import org.springframework.validation.annotation.Validated;import org.springframework.web.bind.annotation.*;

@Validated @RestController @RequestMapping("/control/v1")
public class ReleaseController{
 private final ReleaseApplicationService service;private final ObjectMapper json;public ReleaseController(ReleaseApplicationService s,ObjectMapper j){service=s;json=j;}
 @PostMapping("/workspaces")public ResponseEntity<WorkspaceResponse>create(@Valid@RequestBody CreateWorkspace r,@RequestHeader("X-Operator")@NotBlank@Size(max=100)String actor){var w=service.create(r.workspaceCode,r.workspaceName,r.baseBundleId,r.environmentCode,r.riskLevel,r.ownerCode,actor);return ResponseEntity.created(URI.create("/control/v1/workspaces/"+w.id())).body(workspace(w));}
 @GetMapping("/workspaces")public List<WorkspaceResponse>list(){return service.list().stream().map(this::workspace).toList();}@GetMapping("/workspaces/{id}")public WorkspaceResponse get(@PathVariable@Min(1)long id){return workspace(service.get(id));}
 @PostMapping("/workspaces/{id}/assets/binding-version")public ResponseEntity<AssetResponse>asset(@PathVariable@Min(1)long id,@Valid@RequestBody AddAsset r,@RequestHeader("X-Operator")@NotBlank@Size(max=100)String actor){var a=service.addBindingVersion(id,r.bindingId,r.bindingVersionId,r.changeType,r.dependencyMetadata,actor);return ResponseEntity.created(URI.create("/control/v1/workspaces/"+id+"/assets/"+a.id())).body(asset(a));}
 @GetMapping("/workspaces/{id}/assets")public List<AssetResponse>assets(@PathVariable@Min(1)long id){return service.assets(id).stream().map(this::asset).toList();}
 @GetMapping("/workspaces/{id}/verifications")public List<VerificationResponse>verifications(@PathVariable@Min(1)long id){return service.verifications(id).stream().map(this::verification).toList();}
 @PostMapping("/workspaces/{id}:submit-review")public WorkspaceResponse review(@PathVariable@Min(1)long id,@Valid@RequestBody Transition r,@RequestHeader("X-Operator")@NotBlank@Size(max=100)String actor){return workspace(service.submitReview(id,r.rowVersion,actor));}
 @PostMapping("/workspaces/{id}/approvals")public ApprovalResponse approval(@PathVariable@Min(1)long id,@Valid@RequestBody Decide r,@RequestHeader("X-Operator")@NotBlank@Size(max=100)String actor){return approval(service.decide(id,r.approvalStage,r.decision,r.decisionComment,r.evidenceSnapshot,r.rowVersion,actor));}
 @GetMapping("/workspaces/{id}/approvals")public List<ApprovalResponse>approvals(@PathVariable@Min(1)long id){return service.approvals(id).stream().map(this::approval).toList();}
 @PostMapping("/workspaces/{id}/bundles")public ResponseEntity<BundleResponse>compile(@PathVariable@Min(1)long id,@Valid@RequestBody Compile r,@RequestHeader("X-Operator")@NotBlank@Size(max=100)String actor){var b=service.compile(id,r.bundleCode,r.bundleVersion,r.rowVersion,actor);return ResponseEntity.created(URI.create("/control/v1/bundles/"+b.id())).body(bundle(b));}
 @GetMapping("/workspaces/{id}/bundles")public List<BundleResponse>bundles(@PathVariable@Min(1)long id){return service.bundles(id).stream().map(this::bundle).toList();}
 @GetMapping("/bundles/{id}")public BundleResponse bundle(@PathVariable@Min(1)long id){return bundle(service.bundle(id));}@PostMapping("/bundles/{id}:publish")public BundleResponse publish(@PathVariable@Min(1)long id,@RequestHeader("X-Operator")@NotBlank@Size(max=100)String actor){return bundle(service.publish(id,actor));}
 private WorkspaceResponse workspace(ConfigurationWorkspace w){return new WorkspaceResponse(w.id(),w.workspaceCode().value(),w.workspaceName(),w.baseBundleId(),w.environmentCode(),w.lifecycleStatus(),w.riskLevel(),w.ownerCode(),w.rowVersion(),w.createdAt(),w.updatedAt());}private AssetResponse asset(WorkspaceAsset a){return new AssetResponse(a.id(),a.workspaceId(),a.assetType(),a.assetCode(),a.assetVersionId(),a.changeType(),read(a.dependencyMetadata()),a.createdAt());}private VerificationResponse verification(VerificationRun v){return new VerificationResponse(v.id(),v.workspaceId(),v.runNo(),v.runType(),v.status(),v.totalCount(),v.passedCount(),v.failedCount(),v.evidenceUri(),read(v.resultSummary()),v.startedAt(),v.finishedAt());}private ApprovalResponse approval(WorkspaceApproval a){return new ApprovalResponse(a.id(),a.workspaceId(),a.approvalStage(),a.approverCode(),a.decision(),a.decisionComment(),read(a.evidenceSnapshot()),a.decidedAt());}private BundleResponse bundle(DeploymentBundleAsset b){return new BundleResponse(b.id(),b.bundleCode(),b.bundleVersion(),b.workspaceId(),b.operationId(),b.bindingVersionId(),b.environmentCode(),read(b.manifestDocument()),b.artifactUri(),b.artifactChecksum(),b.compilerVersion(),b.runtimeCompatibility(),read(b.signatureMetadata()),b.lifecycleStatus(),b.publishedBy(),b.publishedAt(),b.createdAt());}private JsonNode read(String v){try{return json.readTree(v);}catch(JsonProcessingException e){throw new IllegalStateException("Stored release JSON is invalid",e);}}
 public record CreateWorkspace(@NotBlank@Size(max=180)@Pattern(regexp="^[a-z][a-z0-9]*(?:[._-][a-z0-9]+)*$")String workspaceCode,@NotBlank@Size(max=200)String workspaceName,@Positive Long baseBundleId,@NotBlank@Size(max=32)@Pattern(regexp="^[a-z][a-z0-9_-]*$")String environmentCode,@NotNull WorkspaceRiskLevel riskLevel,@NotBlank@Size(max=100)String ownerCode){}public record AddAsset(@Positive long bindingId,@Positive long bindingVersionId,@NotNull WorkspaceChangeType changeType,JsonNode dependencyMetadata){}public record Transition(@PositiveOrZero long rowVersion){}public record Decide(@NotBlank@Size(max=64)String approvalStage,@NotNull ApprovalDecision decision,@Size(max=2000)String decisionComment,JsonNode evidenceSnapshot,@PositiveOrZero long rowVersion){}public record Compile(@NotBlank@Size(max=200)@Pattern(regexp="^[a-z][a-z0-9]*(?:[._-][a-z0-9]+)*$")String bundleCode,@NotBlank@Size(max=64)@Pattern(regexp="^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)$")String bundleVersion,@PositiveOrZero long rowVersion){}
 public record WorkspaceResponse(long id,String workspaceCode,String workspaceName,Long baseBundleId,String environmentCode,WorkspaceLifecycleStatus lifecycleStatus,WorkspaceRiskLevel riskLevel,String ownerCode,long rowVersion,Instant createdAt,Instant updatedAt){}public record AssetResponse(long id,long workspaceId,WorkspaceAssetType assetType,String assetCode,long assetVersionId,WorkspaceChangeType changeType,JsonNode dependencyMetadata,Instant createdAt){}public record VerificationResponse(long id,long workspaceId,long runNo,VerificationRunType runType,VerificationStatus status,int totalCount,int passedCount,int failedCount,String evidenceUri,JsonNode resultSummary,Instant startedAt,Instant finishedAt){}public record ApprovalResponse(long id,long workspaceId,String approvalStage,String approverCode,ApprovalDecision decision,String decisionComment,JsonNode evidenceSnapshot,Instant decidedAt){}public record BundleResponse(long id,String bundleCode,String bundleVersion,long workspaceId,long operationId,long bindingVersionId,String environmentCode,JsonNode manifestDocument,String artifactUri,String artifactChecksum,String compilerVersion,String runtimeCompatibility,JsonNode signatureMetadata,BundleLifecycleStatus lifecycleStatus,String publishedBy,Instant publishedAt,Instant createdAt){}
}
