package com.ftk.tpip.control.application.catalog;
import com.fasterxml.jackson.databind.JsonNode;import com.ftk.tpip.catalog.domain.exception.CanonicalContractCodeAlreadyExistsException;import com.ftk.tpip.catalog.domain.model.*;import com.ftk.tpip.catalog.domain.repository.*;import com.ftk.tpip.shared.*;import java.util.List;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
@Service public class CanonicalContractApplicationService{private final CanonicalContractRepository contracts;private final CanonicalOperationRepository operations;private final CanonicalSchemaContentCanonicalizer canonicalizer;public CanonicalContractApplicationService(CanonicalContractRepository contracts,CanonicalOperationRepository operations,CanonicalSchemaContentCanonicalizer canonicalizer){this.contracts=contracts;this.operations=operations;this.canonicalizer=canonicalizer;}
@Transactional public CanonicalContract create(long operationId,String code,String name,ContractKind kind,String description,String actor){requireActiveOperation(operationId);var c=AssetCode.of(code);if(contracts.findByCode(c).isPresent())throw new CanonicalContractCodeAlreadyExistsException(c.value());return contracts.create(CanonicalContract.create(operationId,c,name,kind,description),actor(actor));}
@Transactional(readOnly=true)public CanonicalContract get(long id){return contracts.findById(id).orElseThrow(()->new CanonicalContractNotFoundException(id));}
@Transactional(readOnly=true)public CanonicalContractPage list(Long operationId,ContractKind kind,String keyword,CanonicalContractStatus status,int page,int size){if(page<0||size<1||size>200)throw new IllegalArgumentException("page must be non-negative and size must be between 1 and 200");long o=(long)page*size;if(o>Integer.MAX_VALUE)throw new IllegalArgumentException("page offset is too large");var q=new CanonicalContractQuery(operationId,kind,keyword,status,(int)o,size);return new CanonicalContractPage(contracts.findAll(q),page,size,contracts.count(q));}
@Transactional public CanonicalContract update(long id,String name,String description,CanonicalContractStatus status,long version,String actor){var c=get(id);if(status==CanonicalContractStatus.ACTIVE)requireActiveOperation(c.operationId());return contracts.update(c.revise(name,description,status,version),actor(actor));}
@Transactional public CanonicalContractVersion createVersion(long contractId,String semanticVersion,SchemaStandard standard,JsonNode schema,JsonNode example,CompatibilityMode mode,String actor){var c=get(contractId);if(c.status()!=CanonicalContractStatus.ACTIVE)throw new IllegalArgumentException("Canonical contract must be ACTIVE");requireActiveOperation(c.operationId());var content=canonicalizer.canonicalize(standard,schema,example,mode);var draft=CanonicalContractVersion.draft(contractId,SemanticVersion.parse(semanticVersion),standard,content.schemaDocument(),content.exampleDocument(),mode,content.checksum());return contracts.createVersion(draft,actor(actor));}
@Transactional(readOnly=true)public List<CanonicalContractVersion> versions(long id){get(id);return contracts.findVersions(id);}@Transactional(readOnly=true)public CanonicalContractVersion version(long id,long versionId){get(id);return contracts.findVersion(id,versionId).orElseThrow(()->new CanonicalContractVersionNotFoundException(id,versionId));}@Transactional public CanonicalContractVersion publish(long id,long versionId,String actor){var c=get(id);if(c.status()!=CanonicalContractStatus.ACTIVE)throw new IllegalArgumentException("Canonical contract must be ACTIVE");requireActiveOperation(c.operationId());version(id,versionId);return contracts.publishVersion(id,versionId,actor(actor));}
private void requireActiveOperation(long id){var o=operations.findById(id).orElseThrow(()->new IllegalArgumentException("operationId does not exist: "+id));if(o.status()!=OperationStatus.ACTIVE)throw new IllegalArgumentException("operationId must reference an ACTIVE canonical operation");}private static String actor(String a){if(a==null||a.isBlank()||a.trim().length()>100)throw new IllegalArgumentException("X-Operator is blank or too long");return a.trim();}}
