package com.ftk.tpip.control.application.catalog;
import com.ftk.tpip.catalog.domain.exception.CatalogCodeAlreadyExistsException;import com.ftk.tpip.catalog.domain.model.*;import com.ftk.tpip.catalog.domain.repository.CatalogHierarchyRepository;import com.ftk.tpip.shared.AssetCode;import java.util.List;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
@Service public class CatalogHierarchyApplicationService{private final CatalogHierarchyRepository r;public CatalogHierarchyApplicationService(CatalogHierarchyRepository r){this.r=r;}
@Transactional public BusinessDomain createDomain(String code,String name,String description,String owner,String actor){var c=AssetCode.of(code);if(r.findDomainByCode(c).isPresent())throw new CatalogCodeAlreadyExistsException("Business domain",c.value());return r.createDomain(BusinessDomain.create(c,name,description,owner),actor(actor));}
@Transactional(readOnly=true) public BusinessDomain getDomain(long id){return r.findDomain(id).orElseThrow(()->new CatalogAssetNotFoundException("Business domain",id));}
@Transactional(readOnly=true) public Page<BusinessDomain> domains(String keyword,CatalogAssetStatus status,int page,int size){int o=offset(page,size);return new Page<>(r.findDomains(keyword,status,o,size),page,size,r.countDomains(keyword,status));}
@Transactional public BusinessDomain updateDomain(long id,String name,String description,String owner,CatalogAssetStatus status,long version,String actor){return r.updateDomain(getDomain(id).revise(name,description,owner,status,version),actor(actor));}
@Transactional public CanonicalCapability createCapability(long domainId,String code,String name,String description,String owner,String actor){var d=getDomain(domainId);if(d.status()!=CatalogAssetStatus.ACTIVE)throw new IllegalArgumentException("domainId must reference an ACTIVE business domain");var c=AssetCode.of(code);if(r.findCapabilityByCode(c).isPresent())throw new CatalogCodeAlreadyExistsException("Capability",c.value());return r.createCapability(CanonicalCapability.create(domainId,c,name,description,owner),actor(actor));}
@Transactional(readOnly=true) public CanonicalCapability getCapability(long id){return r.findCapability(id).orElseThrow(()->new CatalogAssetNotFoundException("Capability",id));}
@Transactional(readOnly=true) public Page<CanonicalCapability> capabilities(Long domainId,String keyword,CatalogAssetStatus status,int page,int size){int o=offset(page,size);return new Page<>(r.findCapabilities(domainId,keyword,status,o,size),page,size,r.countCapabilities(domainId,keyword,status));}
@Transactional public CanonicalCapability updateCapability(long id,String name,String description,String owner,CatalogAssetStatus status,long version,String actor){var c=getCapability(id);if(status==CatalogAssetStatus.ACTIVE&&getDomain(c.domainId()).status()!=CatalogAssetStatus.ACTIVE)throw new IllegalArgumentException("Cannot activate a capability under an INACTIVE domain");return r.updateCapability(c.revise(name,description,owner,status,version),actor(actor));}
private static int offset(int p,int s){if(p<0||s<1||s>200)throw new IllegalArgumentException("page must be non-negative and size must be between 1 and 200");long o=(long)p*s;if(o>Integer.MAX_VALUE)throw new IllegalArgumentException("page offset is too large");return(int)o;}private static String actor(String a){if(a==null||a.isBlank()||a.trim().length()>100)throw new IllegalArgumentException("X-Operator is blank or too long");return a.trim();}public record Page<T>(List<T> items,int page,int size,long totalElements){}
}
